/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Advisor
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class Advisor {
  @SerializedName("AuditorName")
  private String auditorName = null;

  @SerializedName("SolicitorName")
  private String solicitorName = null;

  public Advisor auditorName(String auditorName) {
    this.auditorName = auditorName;
    return this;
  }

   /**
   * Get auditorName
   * @return auditorName
  **/
  @ApiModelProperty(value = "")
  public String getAuditorName() {
    return auditorName;
  }

  public void setAuditorName(String auditorName) {
    this.auditorName = auditorName;
  }

  public Advisor solicitorName(String solicitorName) {
    this.solicitorName = solicitorName;
    return this;
  }

   /**
   * Get solicitorName
   * @return solicitorName
  **/
  @ApiModelProperty(value = "")
  public String getSolicitorName() {
    return solicitorName;
  }

  public void setSolicitorName(String solicitorName) {
    this.solicitorName = solicitorName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Advisor advisor = (Advisor) o;
    return Objects.equals(this.auditorName, advisor.auditorName) &&
        Objects.equals(this.solicitorName, advisor.solicitorName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auditorName, solicitorName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Advisor {\n");
    
    sb.append("    auditorName: ").append(toIndentedString(auditorName)).append("\n");
    sb.append("    solicitorName: ").append(toIndentedString(solicitorName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

