/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FinancialValueDecimal;
import java.io.IOException;

/**
 * BalanceSheet
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class BalanceSheet {
  @SerializedName("LandAndBuildings")
  private FinancialValueDecimal landAndBuildings = null;

  @SerializedName("PlantAndMachinery")
  private FinancialValueDecimal plantAndMachinery = null;

  @SerializedName("OtherTangibleAssets")
  private FinancialValueDecimal otherTangibleAssets = null;

  @SerializedName("TotalTangibleAssets")
  private FinancialValueDecimal totalTangibleAssets = null;

  @SerializedName("Goodwill")
  private FinancialValueDecimal goodwill = null;

  @SerializedName("OtherIntangibleAssets")
  private FinancialValueDecimal otherIntangibleAssets = null;

  @SerializedName("TotalIntangibleAssets")
  private FinancialValueDecimal totalIntangibleAssets = null;

  @SerializedName("Investments")
  private FinancialValueDecimal investments = null;

  @SerializedName("LoansToGroup")
  private FinancialValueDecimal loansToGroup = null;

  @SerializedName("OtherLoans")
  private FinancialValueDecimal otherLoans = null;

  @SerializedName("MiscellaneousFixedAssets")
  private FinancialValueDecimal miscellaneousFixedAssets = null;

  @SerializedName("TotalOtherFixedAssets")
  private FinancialValueDecimal totalOtherFixedAssets = null;

  @SerializedName("TotalFixedAssets")
  private FinancialValueDecimal totalFixedAssets = null;

  @SerializedName("RawMaterials")
  private FinancialValueDecimal rawMaterials = null;

  @SerializedName("WorkInProgress")
  private FinancialValueDecimal workInProgress = null;

  @SerializedName("FinishedGoods")
  private FinancialValueDecimal finishedGoods = null;

  @SerializedName("OtherInventories")
  private FinancialValueDecimal otherInventories = null;

  @SerializedName("TotalInventories")
  private FinancialValueDecimal totalInventories = null;

  @SerializedName("TradeReceivables")
  private FinancialValueDecimal tradeReceivables = null;

  @SerializedName("GroupReceivables")
  private FinancialValueDecimal groupReceivables = null;

  @SerializedName("ReceivablesDueAfter1Year")
  private FinancialValueDecimal receivablesDueAfter1Year = null;

  @SerializedName("MiscellaneousReceivables")
  private FinancialValueDecimal miscellaneousReceivables = null;

  @SerializedName("TotalReceivables")
  private FinancialValueDecimal totalReceivables = null;

  @SerializedName("Cash")
  private FinancialValueDecimal cash = null;

  @SerializedName("OtherCurrentAssets")
  private FinancialValueDecimal otherCurrentAssets = null;

  @SerializedName("TotalCurrentAssets")
  private FinancialValueDecimal totalCurrentAssets = null;

  @SerializedName("TotalAssets")
  private FinancialValueDecimal totalAssets = null;

  @SerializedName("TradePayables")
  private FinancialValueDecimal tradePayables = null;

  @SerializedName("BankLiabilities")
  private FinancialValueDecimal bankLiabilities = null;

  @SerializedName("OtherLoansOrFinance")
  private FinancialValueDecimal otherLoansOrFinance = null;

  @SerializedName("GroupPayables")
  private FinancialValueDecimal groupPayables = null;

  @SerializedName("MiscellaneousLiabilities")
  private FinancialValueDecimal miscellaneousLiabilities = null;

  @SerializedName("TotalCurrentLiabilities")
  private FinancialValueDecimal totalCurrentLiabilities = null;

  @SerializedName("TradePayablesDueAfter1Year")
  private FinancialValueDecimal tradePayablesDueAfter1Year = null;

  @SerializedName("BankLiabilitiesDueAfter1Year")
  private FinancialValueDecimal bankLiabilitiesDueAfter1Year = null;

  @SerializedName("OtherLoansOrFinanceDueAfter1Year")
  private FinancialValueDecimal otherLoansOrFinanceDueAfter1Year = null;

  @SerializedName("GroupPayablesDueAfter1Year")
  private FinancialValueDecimal groupPayablesDueAfter1Year = null;

  @SerializedName("MiscellaneousLiabilitiesDueAfter1Year")
  private FinancialValueDecimal miscellaneousLiabilitiesDueAfter1Year = null;

  @SerializedName("TotalLongTermLiabilities")
  private FinancialValueDecimal totalLongTermLiabilities = null;

  @SerializedName("TotalLiabilities")
  private FinancialValueDecimal totalLiabilities = null;

  @SerializedName("CalledUpShareCapital")
  private FinancialValueDecimal calledUpShareCapital = null;

  @SerializedName("SharePremium")
  private FinancialValueDecimal sharePremium = null;

  @SerializedName("RevenueReserves")
  private FinancialValueDecimal revenueReserves = null;

  @SerializedName("OtherReserves")
  private FinancialValueDecimal otherReserves = null;

  @SerializedName("TotalShareholdersEquity")
  private FinancialValueDecimal totalShareholdersEquity = null;

  public BalanceSheet landAndBuildings(FinancialValueDecimal landAndBuildings) {
    this.landAndBuildings = landAndBuildings;
    return this;
  }

   /**
   * Get landAndBuildings
   * @return landAndBuildings
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getLandAndBuildings() {
    return landAndBuildings;
  }

  public void setLandAndBuildings(FinancialValueDecimal landAndBuildings) {
    this.landAndBuildings = landAndBuildings;
  }

  public BalanceSheet plantAndMachinery(FinancialValueDecimal plantAndMachinery) {
    this.plantAndMachinery = plantAndMachinery;
    return this;
  }

   /**
   * Get plantAndMachinery
   * @return plantAndMachinery
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getPlantAndMachinery() {
    return plantAndMachinery;
  }

  public void setPlantAndMachinery(FinancialValueDecimal plantAndMachinery) {
    this.plantAndMachinery = plantAndMachinery;
  }

  public BalanceSheet otherTangibleAssets(FinancialValueDecimal otherTangibleAssets) {
    this.otherTangibleAssets = otherTangibleAssets;
    return this;
  }

   /**
   * Get otherTangibleAssets
   * @return otherTangibleAssets
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getOtherTangibleAssets() {
    return otherTangibleAssets;
  }

  public void setOtherTangibleAssets(FinancialValueDecimal otherTangibleAssets) {
    this.otherTangibleAssets = otherTangibleAssets;
  }

  public BalanceSheet totalTangibleAssets(FinancialValueDecimal totalTangibleAssets) {
    this.totalTangibleAssets = totalTangibleAssets;
    return this;
  }

   /**
   * Get totalTangibleAssets
   * @return totalTangibleAssets
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTotalTangibleAssets() {
    return totalTangibleAssets;
  }

  public void setTotalTangibleAssets(FinancialValueDecimal totalTangibleAssets) {
    this.totalTangibleAssets = totalTangibleAssets;
  }

  public BalanceSheet goodwill(FinancialValueDecimal goodwill) {
    this.goodwill = goodwill;
    return this;
  }

   /**
   * Get goodwill
   * @return goodwill
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getGoodwill() {
    return goodwill;
  }

  public void setGoodwill(FinancialValueDecimal goodwill) {
    this.goodwill = goodwill;
  }

  public BalanceSheet otherIntangibleAssets(FinancialValueDecimal otherIntangibleAssets) {
    this.otherIntangibleAssets = otherIntangibleAssets;
    return this;
  }

   /**
   * Get otherIntangibleAssets
   * @return otherIntangibleAssets
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getOtherIntangibleAssets() {
    return otherIntangibleAssets;
  }

  public void setOtherIntangibleAssets(FinancialValueDecimal otherIntangibleAssets) {
    this.otherIntangibleAssets = otherIntangibleAssets;
  }

  public BalanceSheet totalIntangibleAssets(FinancialValueDecimal totalIntangibleAssets) {
    this.totalIntangibleAssets = totalIntangibleAssets;
    return this;
  }

   /**
   * Get totalIntangibleAssets
   * @return totalIntangibleAssets
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTotalIntangibleAssets() {
    return totalIntangibleAssets;
  }

  public void setTotalIntangibleAssets(FinancialValueDecimal totalIntangibleAssets) {
    this.totalIntangibleAssets = totalIntangibleAssets;
  }

  public BalanceSheet investments(FinancialValueDecimal investments) {
    this.investments = investments;
    return this;
  }

   /**
   * Get investments
   * @return investments
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getInvestments() {
    return investments;
  }

  public void setInvestments(FinancialValueDecimal investments) {
    this.investments = investments;
  }

  public BalanceSheet loansToGroup(FinancialValueDecimal loansToGroup) {
    this.loansToGroup = loansToGroup;
    return this;
  }

   /**
   * Get loansToGroup
   * @return loansToGroup
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getLoansToGroup() {
    return loansToGroup;
  }

  public void setLoansToGroup(FinancialValueDecimal loansToGroup) {
    this.loansToGroup = loansToGroup;
  }

  public BalanceSheet otherLoans(FinancialValueDecimal otherLoans) {
    this.otherLoans = otherLoans;
    return this;
  }

   /**
   * Get otherLoans
   * @return otherLoans
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getOtherLoans() {
    return otherLoans;
  }

  public void setOtherLoans(FinancialValueDecimal otherLoans) {
    this.otherLoans = otherLoans;
  }

  public BalanceSheet miscellaneousFixedAssets(FinancialValueDecimal miscellaneousFixedAssets) {
    this.miscellaneousFixedAssets = miscellaneousFixedAssets;
    return this;
  }

   /**
   * Get miscellaneousFixedAssets
   * @return miscellaneousFixedAssets
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getMiscellaneousFixedAssets() {
    return miscellaneousFixedAssets;
  }

  public void setMiscellaneousFixedAssets(FinancialValueDecimal miscellaneousFixedAssets) {
    this.miscellaneousFixedAssets = miscellaneousFixedAssets;
  }

  public BalanceSheet totalOtherFixedAssets(FinancialValueDecimal totalOtherFixedAssets) {
    this.totalOtherFixedAssets = totalOtherFixedAssets;
    return this;
  }

   /**
   * Get totalOtherFixedAssets
   * @return totalOtherFixedAssets
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTotalOtherFixedAssets() {
    return totalOtherFixedAssets;
  }

  public void setTotalOtherFixedAssets(FinancialValueDecimal totalOtherFixedAssets) {
    this.totalOtherFixedAssets = totalOtherFixedAssets;
  }

  public BalanceSheet totalFixedAssets(FinancialValueDecimal totalFixedAssets) {
    this.totalFixedAssets = totalFixedAssets;
    return this;
  }

   /**
   * Get totalFixedAssets
   * @return totalFixedAssets
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTotalFixedAssets() {
    return totalFixedAssets;
  }

  public void setTotalFixedAssets(FinancialValueDecimal totalFixedAssets) {
    this.totalFixedAssets = totalFixedAssets;
  }

  public BalanceSheet rawMaterials(FinancialValueDecimal rawMaterials) {
    this.rawMaterials = rawMaterials;
    return this;
  }

   /**
   * Get rawMaterials
   * @return rawMaterials
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getRawMaterials() {
    return rawMaterials;
  }

  public void setRawMaterials(FinancialValueDecimal rawMaterials) {
    this.rawMaterials = rawMaterials;
  }

  public BalanceSheet workInProgress(FinancialValueDecimal workInProgress) {
    this.workInProgress = workInProgress;
    return this;
  }

   /**
   * Get workInProgress
   * @return workInProgress
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getWorkInProgress() {
    return workInProgress;
  }

  public void setWorkInProgress(FinancialValueDecimal workInProgress) {
    this.workInProgress = workInProgress;
  }

  public BalanceSheet finishedGoods(FinancialValueDecimal finishedGoods) {
    this.finishedGoods = finishedGoods;
    return this;
  }

   /**
   * Get finishedGoods
   * @return finishedGoods
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getFinishedGoods() {
    return finishedGoods;
  }

  public void setFinishedGoods(FinancialValueDecimal finishedGoods) {
    this.finishedGoods = finishedGoods;
  }

  public BalanceSheet otherInventories(FinancialValueDecimal otherInventories) {
    this.otherInventories = otherInventories;
    return this;
  }

   /**
   * Get otherInventories
   * @return otherInventories
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getOtherInventories() {
    return otherInventories;
  }

  public void setOtherInventories(FinancialValueDecimal otherInventories) {
    this.otherInventories = otherInventories;
  }

  public BalanceSheet totalInventories(FinancialValueDecimal totalInventories) {
    this.totalInventories = totalInventories;
    return this;
  }

   /**
   * Get totalInventories
   * @return totalInventories
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTotalInventories() {
    return totalInventories;
  }

  public void setTotalInventories(FinancialValueDecimal totalInventories) {
    this.totalInventories = totalInventories;
  }

  public BalanceSheet tradeReceivables(FinancialValueDecimal tradeReceivables) {
    this.tradeReceivables = tradeReceivables;
    return this;
  }

   /**
   * Get tradeReceivables
   * @return tradeReceivables
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTradeReceivables() {
    return tradeReceivables;
  }

  public void setTradeReceivables(FinancialValueDecimal tradeReceivables) {
    this.tradeReceivables = tradeReceivables;
  }

  public BalanceSheet groupReceivables(FinancialValueDecimal groupReceivables) {
    this.groupReceivables = groupReceivables;
    return this;
  }

   /**
   * Get groupReceivables
   * @return groupReceivables
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getGroupReceivables() {
    return groupReceivables;
  }

  public void setGroupReceivables(FinancialValueDecimal groupReceivables) {
    this.groupReceivables = groupReceivables;
  }

  public BalanceSheet receivablesDueAfter1Year(FinancialValueDecimal receivablesDueAfter1Year) {
    this.receivablesDueAfter1Year = receivablesDueAfter1Year;
    return this;
  }

   /**
   * Get receivablesDueAfter1Year
   * @return receivablesDueAfter1Year
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getReceivablesDueAfter1Year() {
    return receivablesDueAfter1Year;
  }

  public void setReceivablesDueAfter1Year(FinancialValueDecimal receivablesDueAfter1Year) {
    this.receivablesDueAfter1Year = receivablesDueAfter1Year;
  }

  public BalanceSheet miscellaneousReceivables(FinancialValueDecimal miscellaneousReceivables) {
    this.miscellaneousReceivables = miscellaneousReceivables;
    return this;
  }

   /**
   * Get miscellaneousReceivables
   * @return miscellaneousReceivables
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getMiscellaneousReceivables() {
    return miscellaneousReceivables;
  }

  public void setMiscellaneousReceivables(FinancialValueDecimal miscellaneousReceivables) {
    this.miscellaneousReceivables = miscellaneousReceivables;
  }

  public BalanceSheet totalReceivables(FinancialValueDecimal totalReceivables) {
    this.totalReceivables = totalReceivables;
    return this;
  }

   /**
   * Get totalReceivables
   * @return totalReceivables
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTotalReceivables() {
    return totalReceivables;
  }

  public void setTotalReceivables(FinancialValueDecimal totalReceivables) {
    this.totalReceivables = totalReceivables;
  }

  public BalanceSheet cash(FinancialValueDecimal cash) {
    this.cash = cash;
    return this;
  }

   /**
   * Get cash
   * @return cash
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getCash() {
    return cash;
  }

  public void setCash(FinancialValueDecimal cash) {
    this.cash = cash;
  }

  public BalanceSheet otherCurrentAssets(FinancialValueDecimal otherCurrentAssets) {
    this.otherCurrentAssets = otherCurrentAssets;
    return this;
  }

   /**
   * Get otherCurrentAssets
   * @return otherCurrentAssets
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getOtherCurrentAssets() {
    return otherCurrentAssets;
  }

  public void setOtherCurrentAssets(FinancialValueDecimal otherCurrentAssets) {
    this.otherCurrentAssets = otherCurrentAssets;
  }

  public BalanceSheet totalCurrentAssets(FinancialValueDecimal totalCurrentAssets) {
    this.totalCurrentAssets = totalCurrentAssets;
    return this;
  }

   /**
   * Get totalCurrentAssets
   * @return totalCurrentAssets
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTotalCurrentAssets() {
    return totalCurrentAssets;
  }

  public void setTotalCurrentAssets(FinancialValueDecimal totalCurrentAssets) {
    this.totalCurrentAssets = totalCurrentAssets;
  }

  public BalanceSheet totalAssets(FinancialValueDecimal totalAssets) {
    this.totalAssets = totalAssets;
    return this;
  }

   /**
   * Get totalAssets
   * @return totalAssets
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTotalAssets() {
    return totalAssets;
  }

  public void setTotalAssets(FinancialValueDecimal totalAssets) {
    this.totalAssets = totalAssets;
  }

  public BalanceSheet tradePayables(FinancialValueDecimal tradePayables) {
    this.tradePayables = tradePayables;
    return this;
  }

   /**
   * Get tradePayables
   * @return tradePayables
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTradePayables() {
    return tradePayables;
  }

  public void setTradePayables(FinancialValueDecimal tradePayables) {
    this.tradePayables = tradePayables;
  }

  public BalanceSheet bankLiabilities(FinancialValueDecimal bankLiabilities) {
    this.bankLiabilities = bankLiabilities;
    return this;
  }

   /**
   * Get bankLiabilities
   * @return bankLiabilities
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getBankLiabilities() {
    return bankLiabilities;
  }

  public void setBankLiabilities(FinancialValueDecimal bankLiabilities) {
    this.bankLiabilities = bankLiabilities;
  }

  public BalanceSheet otherLoansOrFinance(FinancialValueDecimal otherLoansOrFinance) {
    this.otherLoansOrFinance = otherLoansOrFinance;
    return this;
  }

   /**
   * Get otherLoansOrFinance
   * @return otherLoansOrFinance
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getOtherLoansOrFinance() {
    return otherLoansOrFinance;
  }

  public void setOtherLoansOrFinance(FinancialValueDecimal otherLoansOrFinance) {
    this.otherLoansOrFinance = otherLoansOrFinance;
  }

  public BalanceSheet groupPayables(FinancialValueDecimal groupPayables) {
    this.groupPayables = groupPayables;
    return this;
  }

   /**
   * Get groupPayables
   * @return groupPayables
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getGroupPayables() {
    return groupPayables;
  }

  public void setGroupPayables(FinancialValueDecimal groupPayables) {
    this.groupPayables = groupPayables;
  }

  public BalanceSheet miscellaneousLiabilities(FinancialValueDecimal miscellaneousLiabilities) {
    this.miscellaneousLiabilities = miscellaneousLiabilities;
    return this;
  }

   /**
   * Get miscellaneousLiabilities
   * @return miscellaneousLiabilities
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getMiscellaneousLiabilities() {
    return miscellaneousLiabilities;
  }

  public void setMiscellaneousLiabilities(FinancialValueDecimal miscellaneousLiabilities) {
    this.miscellaneousLiabilities = miscellaneousLiabilities;
  }

  public BalanceSheet totalCurrentLiabilities(FinancialValueDecimal totalCurrentLiabilities) {
    this.totalCurrentLiabilities = totalCurrentLiabilities;
    return this;
  }

   /**
   * Get totalCurrentLiabilities
   * @return totalCurrentLiabilities
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTotalCurrentLiabilities() {
    return totalCurrentLiabilities;
  }

  public void setTotalCurrentLiabilities(FinancialValueDecimal totalCurrentLiabilities) {
    this.totalCurrentLiabilities = totalCurrentLiabilities;
  }

  public BalanceSheet tradePayablesDueAfter1Year(FinancialValueDecimal tradePayablesDueAfter1Year) {
    this.tradePayablesDueAfter1Year = tradePayablesDueAfter1Year;
    return this;
  }

   /**
   * Get tradePayablesDueAfter1Year
   * @return tradePayablesDueAfter1Year
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTradePayablesDueAfter1Year() {
    return tradePayablesDueAfter1Year;
  }

  public void setTradePayablesDueAfter1Year(FinancialValueDecimal tradePayablesDueAfter1Year) {
    this.tradePayablesDueAfter1Year = tradePayablesDueAfter1Year;
  }

  public BalanceSheet bankLiabilitiesDueAfter1Year(FinancialValueDecimal bankLiabilitiesDueAfter1Year) {
    this.bankLiabilitiesDueAfter1Year = bankLiabilitiesDueAfter1Year;
    return this;
  }

   /**
   * Get bankLiabilitiesDueAfter1Year
   * @return bankLiabilitiesDueAfter1Year
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getBankLiabilitiesDueAfter1Year() {
    return bankLiabilitiesDueAfter1Year;
  }

  public void setBankLiabilitiesDueAfter1Year(FinancialValueDecimal bankLiabilitiesDueAfter1Year) {
    this.bankLiabilitiesDueAfter1Year = bankLiabilitiesDueAfter1Year;
  }

  public BalanceSheet otherLoansOrFinanceDueAfter1Year(FinancialValueDecimal otherLoansOrFinanceDueAfter1Year) {
    this.otherLoansOrFinanceDueAfter1Year = otherLoansOrFinanceDueAfter1Year;
    return this;
  }

   /**
   * Get otherLoansOrFinanceDueAfter1Year
   * @return otherLoansOrFinanceDueAfter1Year
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getOtherLoansOrFinanceDueAfter1Year() {
    return otherLoansOrFinanceDueAfter1Year;
  }

  public void setOtherLoansOrFinanceDueAfter1Year(FinancialValueDecimal otherLoansOrFinanceDueAfter1Year) {
    this.otherLoansOrFinanceDueAfter1Year = otherLoansOrFinanceDueAfter1Year;
  }

  public BalanceSheet groupPayablesDueAfter1Year(FinancialValueDecimal groupPayablesDueAfter1Year) {
    this.groupPayablesDueAfter1Year = groupPayablesDueAfter1Year;
    return this;
  }

   /**
   * Get groupPayablesDueAfter1Year
   * @return groupPayablesDueAfter1Year
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getGroupPayablesDueAfter1Year() {
    return groupPayablesDueAfter1Year;
  }

  public void setGroupPayablesDueAfter1Year(FinancialValueDecimal groupPayablesDueAfter1Year) {
    this.groupPayablesDueAfter1Year = groupPayablesDueAfter1Year;
  }

  public BalanceSheet miscellaneousLiabilitiesDueAfter1Year(FinancialValueDecimal miscellaneousLiabilitiesDueAfter1Year) {
    this.miscellaneousLiabilitiesDueAfter1Year = miscellaneousLiabilitiesDueAfter1Year;
    return this;
  }

   /**
   * Get miscellaneousLiabilitiesDueAfter1Year
   * @return miscellaneousLiabilitiesDueAfter1Year
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getMiscellaneousLiabilitiesDueAfter1Year() {
    return miscellaneousLiabilitiesDueAfter1Year;
  }

  public void setMiscellaneousLiabilitiesDueAfter1Year(FinancialValueDecimal miscellaneousLiabilitiesDueAfter1Year) {
    this.miscellaneousLiabilitiesDueAfter1Year = miscellaneousLiabilitiesDueAfter1Year;
  }

  public BalanceSheet totalLongTermLiabilities(FinancialValueDecimal totalLongTermLiabilities) {
    this.totalLongTermLiabilities = totalLongTermLiabilities;
    return this;
  }

   /**
   * Get totalLongTermLiabilities
   * @return totalLongTermLiabilities
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTotalLongTermLiabilities() {
    return totalLongTermLiabilities;
  }

  public void setTotalLongTermLiabilities(FinancialValueDecimal totalLongTermLiabilities) {
    this.totalLongTermLiabilities = totalLongTermLiabilities;
  }

  public BalanceSheet totalLiabilities(FinancialValueDecimal totalLiabilities) {
    this.totalLiabilities = totalLiabilities;
    return this;
  }

   /**
   * Get totalLiabilities
   * @return totalLiabilities
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTotalLiabilities() {
    return totalLiabilities;
  }

  public void setTotalLiabilities(FinancialValueDecimal totalLiabilities) {
    this.totalLiabilities = totalLiabilities;
  }

  public BalanceSheet calledUpShareCapital(FinancialValueDecimal calledUpShareCapital) {
    this.calledUpShareCapital = calledUpShareCapital;
    return this;
  }

   /**
   * Get calledUpShareCapital
   * @return calledUpShareCapital
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getCalledUpShareCapital() {
    return calledUpShareCapital;
  }

  public void setCalledUpShareCapital(FinancialValueDecimal calledUpShareCapital) {
    this.calledUpShareCapital = calledUpShareCapital;
  }

  public BalanceSheet sharePremium(FinancialValueDecimal sharePremium) {
    this.sharePremium = sharePremium;
    return this;
  }

   /**
   * Get sharePremium
   * @return sharePremium
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getSharePremium() {
    return sharePremium;
  }

  public void setSharePremium(FinancialValueDecimal sharePremium) {
    this.sharePremium = sharePremium;
  }

  public BalanceSheet revenueReserves(FinancialValueDecimal revenueReserves) {
    this.revenueReserves = revenueReserves;
    return this;
  }

   /**
   * Get revenueReserves
   * @return revenueReserves
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getRevenueReserves() {
    return revenueReserves;
  }

  public void setRevenueReserves(FinancialValueDecimal revenueReserves) {
    this.revenueReserves = revenueReserves;
  }

  public BalanceSheet otherReserves(FinancialValueDecimal otherReserves) {
    this.otherReserves = otherReserves;
    return this;
  }

   /**
   * Get otherReserves
   * @return otherReserves
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getOtherReserves() {
    return otherReserves;
  }

  public void setOtherReserves(FinancialValueDecimal otherReserves) {
    this.otherReserves = otherReserves;
  }

  public BalanceSheet totalShareholdersEquity(FinancialValueDecimal totalShareholdersEquity) {
    this.totalShareholdersEquity = totalShareholdersEquity;
    return this;
  }

   /**
   * Get totalShareholdersEquity
   * @return totalShareholdersEquity
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getTotalShareholdersEquity() {
    return totalShareholdersEquity;
  }

  public void setTotalShareholdersEquity(FinancialValueDecimal totalShareholdersEquity) {
    this.totalShareholdersEquity = totalShareholdersEquity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalanceSheet balanceSheet = (BalanceSheet) o;
    return Objects.equals(this.landAndBuildings, balanceSheet.landAndBuildings) &&
        Objects.equals(this.plantAndMachinery, balanceSheet.plantAndMachinery) &&
        Objects.equals(this.otherTangibleAssets, balanceSheet.otherTangibleAssets) &&
        Objects.equals(this.totalTangibleAssets, balanceSheet.totalTangibleAssets) &&
        Objects.equals(this.goodwill, balanceSheet.goodwill) &&
        Objects.equals(this.otherIntangibleAssets, balanceSheet.otherIntangibleAssets) &&
        Objects.equals(this.totalIntangibleAssets, balanceSheet.totalIntangibleAssets) &&
        Objects.equals(this.investments, balanceSheet.investments) &&
        Objects.equals(this.loansToGroup, balanceSheet.loansToGroup) &&
        Objects.equals(this.otherLoans, balanceSheet.otherLoans) &&
        Objects.equals(this.miscellaneousFixedAssets, balanceSheet.miscellaneousFixedAssets) &&
        Objects.equals(this.totalOtherFixedAssets, balanceSheet.totalOtherFixedAssets) &&
        Objects.equals(this.totalFixedAssets, balanceSheet.totalFixedAssets) &&
        Objects.equals(this.rawMaterials, balanceSheet.rawMaterials) &&
        Objects.equals(this.workInProgress, balanceSheet.workInProgress) &&
        Objects.equals(this.finishedGoods, balanceSheet.finishedGoods) &&
        Objects.equals(this.otherInventories, balanceSheet.otherInventories) &&
        Objects.equals(this.totalInventories, balanceSheet.totalInventories) &&
        Objects.equals(this.tradeReceivables, balanceSheet.tradeReceivables) &&
        Objects.equals(this.groupReceivables, balanceSheet.groupReceivables) &&
        Objects.equals(this.receivablesDueAfter1Year, balanceSheet.receivablesDueAfter1Year) &&
        Objects.equals(this.miscellaneousReceivables, balanceSheet.miscellaneousReceivables) &&
        Objects.equals(this.totalReceivables, balanceSheet.totalReceivables) &&
        Objects.equals(this.cash, balanceSheet.cash) &&
        Objects.equals(this.otherCurrentAssets, balanceSheet.otherCurrentAssets) &&
        Objects.equals(this.totalCurrentAssets, balanceSheet.totalCurrentAssets) &&
        Objects.equals(this.totalAssets, balanceSheet.totalAssets) &&
        Objects.equals(this.tradePayables, balanceSheet.tradePayables) &&
        Objects.equals(this.bankLiabilities, balanceSheet.bankLiabilities) &&
        Objects.equals(this.otherLoansOrFinance, balanceSheet.otherLoansOrFinance) &&
        Objects.equals(this.groupPayables, balanceSheet.groupPayables) &&
        Objects.equals(this.miscellaneousLiabilities, balanceSheet.miscellaneousLiabilities) &&
        Objects.equals(this.totalCurrentLiabilities, balanceSheet.totalCurrentLiabilities) &&
        Objects.equals(this.tradePayablesDueAfter1Year, balanceSheet.tradePayablesDueAfter1Year) &&
        Objects.equals(this.bankLiabilitiesDueAfter1Year, balanceSheet.bankLiabilitiesDueAfter1Year) &&
        Objects.equals(this.otherLoansOrFinanceDueAfter1Year, balanceSheet.otherLoansOrFinanceDueAfter1Year) &&
        Objects.equals(this.groupPayablesDueAfter1Year, balanceSheet.groupPayablesDueAfter1Year) &&
        Objects.equals(this.miscellaneousLiabilitiesDueAfter1Year, balanceSheet.miscellaneousLiabilitiesDueAfter1Year) &&
        Objects.equals(this.totalLongTermLiabilities, balanceSheet.totalLongTermLiabilities) &&
        Objects.equals(this.totalLiabilities, balanceSheet.totalLiabilities) &&
        Objects.equals(this.calledUpShareCapital, balanceSheet.calledUpShareCapital) &&
        Objects.equals(this.sharePremium, balanceSheet.sharePremium) &&
        Objects.equals(this.revenueReserves, balanceSheet.revenueReserves) &&
        Objects.equals(this.otherReserves, balanceSheet.otherReserves) &&
        Objects.equals(this.totalShareholdersEquity, balanceSheet.totalShareholdersEquity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(landAndBuildings, plantAndMachinery, otherTangibleAssets, totalTangibleAssets, goodwill, otherIntangibleAssets, totalIntangibleAssets, investments, loansToGroup, otherLoans, miscellaneousFixedAssets, totalOtherFixedAssets, totalFixedAssets, rawMaterials, workInProgress, finishedGoods, otherInventories, totalInventories, tradeReceivables, groupReceivables, receivablesDueAfter1Year, miscellaneousReceivables, totalReceivables, cash, otherCurrentAssets, totalCurrentAssets, totalAssets, tradePayables, bankLiabilities, otherLoansOrFinance, groupPayables, miscellaneousLiabilities, totalCurrentLiabilities, tradePayablesDueAfter1Year, bankLiabilitiesDueAfter1Year, otherLoansOrFinanceDueAfter1Year, groupPayablesDueAfter1Year, miscellaneousLiabilitiesDueAfter1Year, totalLongTermLiabilities, totalLiabilities, calledUpShareCapital, sharePremium, revenueReserves, otherReserves, totalShareholdersEquity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalanceSheet {\n");
    
    sb.append("    landAndBuildings: ").append(toIndentedString(landAndBuildings)).append("\n");
    sb.append("    plantAndMachinery: ").append(toIndentedString(plantAndMachinery)).append("\n");
    sb.append("    otherTangibleAssets: ").append(toIndentedString(otherTangibleAssets)).append("\n");
    sb.append("    totalTangibleAssets: ").append(toIndentedString(totalTangibleAssets)).append("\n");
    sb.append("    goodwill: ").append(toIndentedString(goodwill)).append("\n");
    sb.append("    otherIntangibleAssets: ").append(toIndentedString(otherIntangibleAssets)).append("\n");
    sb.append("    totalIntangibleAssets: ").append(toIndentedString(totalIntangibleAssets)).append("\n");
    sb.append("    investments: ").append(toIndentedString(investments)).append("\n");
    sb.append("    loansToGroup: ").append(toIndentedString(loansToGroup)).append("\n");
    sb.append("    otherLoans: ").append(toIndentedString(otherLoans)).append("\n");
    sb.append("    miscellaneousFixedAssets: ").append(toIndentedString(miscellaneousFixedAssets)).append("\n");
    sb.append("    totalOtherFixedAssets: ").append(toIndentedString(totalOtherFixedAssets)).append("\n");
    sb.append("    totalFixedAssets: ").append(toIndentedString(totalFixedAssets)).append("\n");
    sb.append("    rawMaterials: ").append(toIndentedString(rawMaterials)).append("\n");
    sb.append("    workInProgress: ").append(toIndentedString(workInProgress)).append("\n");
    sb.append("    finishedGoods: ").append(toIndentedString(finishedGoods)).append("\n");
    sb.append("    otherInventories: ").append(toIndentedString(otherInventories)).append("\n");
    sb.append("    totalInventories: ").append(toIndentedString(totalInventories)).append("\n");
    sb.append("    tradeReceivables: ").append(toIndentedString(tradeReceivables)).append("\n");
    sb.append("    groupReceivables: ").append(toIndentedString(groupReceivables)).append("\n");
    sb.append("    receivablesDueAfter1Year: ").append(toIndentedString(receivablesDueAfter1Year)).append("\n");
    sb.append("    miscellaneousReceivables: ").append(toIndentedString(miscellaneousReceivables)).append("\n");
    sb.append("    totalReceivables: ").append(toIndentedString(totalReceivables)).append("\n");
    sb.append("    cash: ").append(toIndentedString(cash)).append("\n");
    sb.append("    otherCurrentAssets: ").append(toIndentedString(otherCurrentAssets)).append("\n");
    sb.append("    totalCurrentAssets: ").append(toIndentedString(totalCurrentAssets)).append("\n");
    sb.append("    totalAssets: ").append(toIndentedString(totalAssets)).append("\n");
    sb.append("    tradePayables: ").append(toIndentedString(tradePayables)).append("\n");
    sb.append("    bankLiabilities: ").append(toIndentedString(bankLiabilities)).append("\n");
    sb.append("    otherLoansOrFinance: ").append(toIndentedString(otherLoansOrFinance)).append("\n");
    sb.append("    groupPayables: ").append(toIndentedString(groupPayables)).append("\n");
    sb.append("    miscellaneousLiabilities: ").append(toIndentedString(miscellaneousLiabilities)).append("\n");
    sb.append("    totalCurrentLiabilities: ").append(toIndentedString(totalCurrentLiabilities)).append("\n");
    sb.append("    tradePayablesDueAfter1Year: ").append(toIndentedString(tradePayablesDueAfter1Year)).append("\n");
    sb.append("    bankLiabilitiesDueAfter1Year: ").append(toIndentedString(bankLiabilitiesDueAfter1Year)).append("\n");
    sb.append("    otherLoansOrFinanceDueAfter1Year: ").append(toIndentedString(otherLoansOrFinanceDueAfter1Year)).append("\n");
    sb.append("    groupPayablesDueAfter1Year: ").append(toIndentedString(groupPayablesDueAfter1Year)).append("\n");
    sb.append("    miscellaneousLiabilitiesDueAfter1Year: ").append(toIndentedString(miscellaneousLiabilitiesDueAfter1Year)).append("\n");
    sb.append("    totalLongTermLiabilities: ").append(toIndentedString(totalLongTermLiabilities)).append("\n");
    sb.append("    totalLiabilities: ").append(toIndentedString(totalLiabilities)).append("\n");
    sb.append("    calledUpShareCapital: ").append(toIndentedString(calledUpShareCapital)).append("\n");
    sb.append("    sharePremium: ").append(toIndentedString(sharePremium)).append("\n");
    sb.append("    revenueReserves: ").append(toIndentedString(revenueReserves)).append("\n");
    sb.append("    otherReserves: ").append(toIndentedString(otherReserves)).append("\n");
    sb.append("    totalShareholdersEquity: ").append(toIndentedString(totalShareholdersEquity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

