/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BankmatchPart
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class BankmatchPart {
  @SerializedName("BankAccountValid")
  private Boolean bankAccountValid = null;

  @SerializedName("BankName")
  private String bankName = null;

  @SerializedName("BranchDetails")
  private String branchDetails = null;

  @SerializedName("BACSPayments")
  private Boolean baCSPayments = null;

  @SerializedName("CHAPSPayments")
  private Boolean chAPSPayments = null;

  @SerializedName("FasterPayments")
  private Boolean fasterPayments = null;

  @SerializedName("DirectDebit")
  private Boolean directDebit = null;

  public BankmatchPart bankAccountValid(Boolean bankAccountValid) {
    this.bankAccountValid = bankAccountValid;
    return this;
  }

   /**
   * Get bankAccountValid
   * @return bankAccountValid
  **/
  @ApiModelProperty(value = "")
  public Boolean getBankAccountValid() {
    return bankAccountValid;
  }

  public void setBankAccountValid(Boolean bankAccountValid) {
    this.bankAccountValid = bankAccountValid;
  }

  public BankmatchPart bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * Get bankName
   * @return bankName
  **/
  @ApiModelProperty(value = "")
  public String getBankName() {
    return bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public BankmatchPart branchDetails(String branchDetails) {
    this.branchDetails = branchDetails;
    return this;
  }

   /**
   * Get branchDetails
   * @return branchDetails
  **/
  @ApiModelProperty(value = "")
  public String getBranchDetails() {
    return branchDetails;
  }

  public void setBranchDetails(String branchDetails) {
    this.branchDetails = branchDetails;
  }

  public BankmatchPart baCSPayments(Boolean baCSPayments) {
    this.baCSPayments = baCSPayments;
    return this;
  }

   /**
   * Get baCSPayments
   * @return baCSPayments
  **/
  @ApiModelProperty(value = "")
  public Boolean getBaCSPayments() {
    return baCSPayments;
  }

  public void setBaCSPayments(Boolean baCSPayments) {
    this.baCSPayments = baCSPayments;
  }

  public BankmatchPart chAPSPayments(Boolean chAPSPayments) {
    this.chAPSPayments = chAPSPayments;
    return this;
  }

   /**
   * Get chAPSPayments
   * @return chAPSPayments
  **/
  @ApiModelProperty(value = "")
  public Boolean getChAPSPayments() {
    return chAPSPayments;
  }

  public void setChAPSPayments(Boolean chAPSPayments) {
    this.chAPSPayments = chAPSPayments;
  }

  public BankmatchPart fasterPayments(Boolean fasterPayments) {
    this.fasterPayments = fasterPayments;
    return this;
  }

   /**
   * Get fasterPayments
   * @return fasterPayments
  **/
  @ApiModelProperty(value = "")
  public Boolean getFasterPayments() {
    return fasterPayments;
  }

  public void setFasterPayments(Boolean fasterPayments) {
    this.fasterPayments = fasterPayments;
  }

  public BankmatchPart directDebit(Boolean directDebit) {
    this.directDebit = directDebit;
    return this;
  }

   /**
   * Get directDebit
   * @return directDebit
  **/
  @ApiModelProperty(value = "")
  public Boolean getDirectDebit() {
    return directDebit;
  }

  public void setDirectDebit(Boolean directDebit) {
    this.directDebit = directDebit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankmatchPart bankmatchPart = (BankmatchPart) o;
    return Objects.equals(this.bankAccountValid, bankmatchPart.bankAccountValid) &&
        Objects.equals(this.bankName, bankmatchPart.bankName) &&
        Objects.equals(this.branchDetails, bankmatchPart.branchDetails) &&
        Objects.equals(this.baCSPayments, bankmatchPart.baCSPayments) &&
        Objects.equals(this.chAPSPayments, bankmatchPart.chAPSPayments) &&
        Objects.equals(this.fasterPayments, bankmatchPart.fasterPayments) &&
        Objects.equals(this.directDebit, bankmatchPart.directDebit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankAccountValid, bankName, branchDetails, baCSPayments, chAPSPayments, fasterPayments, directDebit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankmatchPart {\n");
    
    sb.append("    bankAccountValid: ").append(toIndentedString(bankAccountValid)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    branchDetails: ").append(toIndentedString(branchDetails)).append("\n");
    sb.append("    baCSPayments: ").append(toIndentedString(baCSPayments)).append("\n");
    sb.append("    chAPSPayments: ").append(toIndentedString(chAPSPayments)).append("\n");
    sb.append("    fasterPayments: ").append(toIndentedString(fasterPayments)).append("\n");
    sb.append("    directDebit: ").append(toIndentedString(directDebit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

