/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ContactTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class ContactTO {
  @SerializedName("telephoneNumber")
  private String telephoneNumber = null;

  @SerializedName("alternativeTelephoneNumber")
  private String alternativeTelephoneNumber = null;

  @SerializedName("mobileTelephoneNumber")
  private String mobileTelephoneNumber = null;

  @SerializedName("faxNumber")
  private String faxNumber = null;

  @SerializedName("emailAddress")
  private String emailAddress = null;

  public ContactTO telephoneNumber(String telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
    return this;
  }

   /**
   * Get telephoneNumber
   * @return telephoneNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTelephoneNumber() {
    return telephoneNumber;
  }

  public void setTelephoneNumber(String telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
  }

  public ContactTO alternativeTelephoneNumber(String alternativeTelephoneNumber) {
    this.alternativeTelephoneNumber = alternativeTelephoneNumber;
    return this;
  }

   /**
   * Get alternativeTelephoneNumber
   * @return alternativeTelephoneNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAlternativeTelephoneNumber() {
    return alternativeTelephoneNumber;
  }

  public void setAlternativeTelephoneNumber(String alternativeTelephoneNumber) {
    this.alternativeTelephoneNumber = alternativeTelephoneNumber;
  }

  public ContactTO mobileTelephoneNumber(String mobileTelephoneNumber) {
    this.mobileTelephoneNumber = mobileTelephoneNumber;
    return this;
  }

   /**
   * Get mobileTelephoneNumber
   * @return mobileTelephoneNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMobileTelephoneNumber() {
    return mobileTelephoneNumber;
  }

  public void setMobileTelephoneNumber(String mobileTelephoneNumber) {
    this.mobileTelephoneNumber = mobileTelephoneNumber;
  }

  public ContactTO faxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
    return this;
  }

   /**
   * Get faxNumber
   * @return faxNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public String getFaxNumber() {
    return faxNumber;
  }

  public void setFaxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
  }

  public ContactTO emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Get emailAddress
   * @return emailAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContactTO contactTO = (ContactTO) o;
    return Objects.equals(this.telephoneNumber, contactTO.telephoneNumber) &&
        Objects.equals(this.alternativeTelephoneNumber, contactTO.alternativeTelephoneNumber) &&
        Objects.equals(this.mobileTelephoneNumber, contactTO.mobileTelephoneNumber) &&
        Objects.equals(this.faxNumber, contactTO.faxNumber) &&
        Objects.equals(this.emailAddress, contactTO.emailAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(telephoneNumber, alternativeTelephoneNumber, mobileTelephoneNumber, faxNumber, emailAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContactTO {\n");
    
    sb.append("    telephoneNumber: ").append(toIndentedString(telephoneNumber)).append("\n");
    sb.append("    alternativeTelephoneNumber: ").append(toIndentedString(alternativeTelephoneNumber)).append("\n");
    sb.append("    mobileTelephoneNumber: ").append(toIndentedString(mobileTelephoneNumber)).append("\n");
    sb.append("    faxNumber: ").append(toIndentedString(faxNumber)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

