/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DeathscreenResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class DeathscreenResult {
  @SerializedName("Forename")
  private String forename = null;

  @SerializedName("SecondName")
  private String secondName = null;

  @SerializedName("ThirdName")
  private String thirdName = null;

  @SerializedName("FourthName")
  private String fourthName = null;

  @SerializedName("Surname")
  private String surname = null;

  @SerializedName("District")
  private String district = null;

  @SerializedName("DOB")
  private String DOB = null;

  @SerializedName("DOD")
  private String DOD = null;

  @SerializedName("DOR")
  private String DOR = null;

  @SerializedName("VolumeNo")
  private String volumeNo = null;

  @SerializedName("DistNo")
  private String distNo = null;

  @SerializedName("PageNo")
  private String pageNo = null;

  @SerializedName("RegNo")
  private String regNo = null;

  @SerializedName("EntryNo")
  private String entryNo = null;

  @SerializedName("PlaceOfBirth")
  private String placeOfBirth = null;

  @SerializedName("MaidenName")
  private String maidenName = null;

  @SerializedName("GROReference")
  private String grOReference = null;

  @SerializedName("address1")
  private String address1 = null;

  @SerializedName("address2")
  private String address2 = null;

  @SerializedName("address3")
  private String address3 = null;

  @SerializedName("address4")
  private String address4 = null;

  @SerializedName("address5")
  private String address5 = null;

  @SerializedName("postcode")
  private String postcode = null;

  @SerializedName("MatchType")
  private String matchType = null;

  public DeathscreenResult forename(String forename) {
    this.forename = forename;
    return this;
  }

   /**
   * Get forename
   * @return forename
  **/
  @ApiModelProperty(value = "")
  public String getForename() {
    return forename;
  }

  public void setForename(String forename) {
    this.forename = forename;
  }

  public DeathscreenResult secondName(String secondName) {
    this.secondName = secondName;
    return this;
  }

   /**
   * Get secondName
   * @return secondName
  **/
  @ApiModelProperty(value = "")
  public String getSecondName() {
    return secondName;
  }

  public void setSecondName(String secondName) {
    this.secondName = secondName;
  }

  public DeathscreenResult thirdName(String thirdName) {
    this.thirdName = thirdName;
    return this;
  }

   /**
   * Get thirdName
   * @return thirdName
  **/
  @ApiModelProperty(value = "")
  public String getThirdName() {
    return thirdName;
  }

  public void setThirdName(String thirdName) {
    this.thirdName = thirdName;
  }

  public DeathscreenResult fourthName(String fourthName) {
    this.fourthName = fourthName;
    return this;
  }

   /**
   * Get fourthName
   * @return fourthName
  **/
  @ApiModelProperty(value = "")
  public String getFourthName() {
    return fourthName;
  }

  public void setFourthName(String fourthName) {
    this.fourthName = fourthName;
  }

  public DeathscreenResult surname(String surname) {
    this.surname = surname;
    return this;
  }

   /**
   * Get surname
   * @return surname
  **/
  @ApiModelProperty(value = "")
  public String getSurname() {
    return surname;
  }

  public void setSurname(String surname) {
    this.surname = surname;
  }

  public DeathscreenResult district(String district) {
    this.district = district;
    return this;
  }

   /**
   * Get district
   * @return district
  **/
  @ApiModelProperty(value = "")
  public String getDistrict() {
    return district;
  }

  public void setDistrict(String district) {
    this.district = district;
  }

  public DeathscreenResult DOB(String DOB) {
    this.DOB = DOB;
    return this;
  }

   /**
   * Get DOB
   * @return DOB
  **/
  @ApiModelProperty(value = "")
  public String getDOB() {
    return DOB;
  }

  public void setDOB(String DOB) {
    this.DOB = DOB;
  }

  public DeathscreenResult DOD(String DOD) {
    this.DOD = DOD;
    return this;
  }

   /**
   * Get DOD
   * @return DOD
  **/
  @ApiModelProperty(value = "")
  public String getDOD() {
    return DOD;
  }

  public void setDOD(String DOD) {
    this.DOD = DOD;
  }

  public DeathscreenResult DOR(String DOR) {
    this.DOR = DOR;
    return this;
  }

   /**
   * Get DOR
   * @return DOR
  **/
  @ApiModelProperty(value = "")
  public String getDOR() {
    return DOR;
  }

  public void setDOR(String DOR) {
    this.DOR = DOR;
  }

  public DeathscreenResult volumeNo(String volumeNo) {
    this.volumeNo = volumeNo;
    return this;
  }

   /**
   * Get volumeNo
   * @return volumeNo
  **/
  @ApiModelProperty(value = "")
  public String getVolumeNo() {
    return volumeNo;
  }

  public void setVolumeNo(String volumeNo) {
    this.volumeNo = volumeNo;
  }

  public DeathscreenResult distNo(String distNo) {
    this.distNo = distNo;
    return this;
  }

   /**
   * Get distNo
   * @return distNo
  **/
  @ApiModelProperty(value = "")
  public String getDistNo() {
    return distNo;
  }

  public void setDistNo(String distNo) {
    this.distNo = distNo;
  }

  public DeathscreenResult pageNo(String pageNo) {
    this.pageNo = pageNo;
    return this;
  }

   /**
   * Get pageNo
   * @return pageNo
  **/
  @ApiModelProperty(value = "")
  public String getPageNo() {
    return pageNo;
  }

  public void setPageNo(String pageNo) {
    this.pageNo = pageNo;
  }

  public DeathscreenResult regNo(String regNo) {
    this.regNo = regNo;
    return this;
  }

   /**
   * Get regNo
   * @return regNo
  **/
  @ApiModelProperty(value = "")
  public String getRegNo() {
    return regNo;
  }

  public void setRegNo(String regNo) {
    this.regNo = regNo;
  }

  public DeathscreenResult entryNo(String entryNo) {
    this.entryNo = entryNo;
    return this;
  }

   /**
   * Get entryNo
   * @return entryNo
  **/
  @ApiModelProperty(value = "")
  public String getEntryNo() {
    return entryNo;
  }

  public void setEntryNo(String entryNo) {
    this.entryNo = entryNo;
  }

  public DeathscreenResult placeOfBirth(String placeOfBirth) {
    this.placeOfBirth = placeOfBirth;
    return this;
  }

   /**
   * Get placeOfBirth
   * @return placeOfBirth
  **/
  @ApiModelProperty(value = "")
  public String getPlaceOfBirth() {
    return placeOfBirth;
  }

  public void setPlaceOfBirth(String placeOfBirth) {
    this.placeOfBirth = placeOfBirth;
  }

  public DeathscreenResult maidenName(String maidenName) {
    this.maidenName = maidenName;
    return this;
  }

   /**
   * Get maidenName
   * @return maidenName
  **/
  @ApiModelProperty(value = "")
  public String getMaidenName() {
    return maidenName;
  }

  public void setMaidenName(String maidenName) {
    this.maidenName = maidenName;
  }

  public DeathscreenResult grOReference(String grOReference) {
    this.grOReference = grOReference;
    return this;
  }

   /**
   * Get grOReference
   * @return grOReference
  **/
  @ApiModelProperty(value = "")
  public String getGrOReference() {
    return grOReference;
  }

  public void setGrOReference(String grOReference) {
    this.grOReference = grOReference;
  }

  public DeathscreenResult address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Get address1
   * @return address1
  **/
  @ApiModelProperty(value = "")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public DeathscreenResult address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Get address2
   * @return address2
  **/
  @ApiModelProperty(value = "")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public DeathscreenResult address3(String address3) {
    this.address3 = address3;
    return this;
  }

   /**
   * Get address3
   * @return address3
  **/
  @ApiModelProperty(value = "")
  public String getAddress3() {
    return address3;
  }

  public void setAddress3(String address3) {
    this.address3 = address3;
  }

  public DeathscreenResult address4(String address4) {
    this.address4 = address4;
    return this;
  }

   /**
   * Get address4
   * @return address4
  **/
  @ApiModelProperty(value = "")
  public String getAddress4() {
    return address4;
  }

  public void setAddress4(String address4) {
    this.address4 = address4;
  }

  public DeathscreenResult address5(String address5) {
    this.address5 = address5;
    return this;
  }

   /**
   * Get address5
   * @return address5
  **/
  @ApiModelProperty(value = "")
  public String getAddress5() {
    return address5;
  }

  public void setAddress5(String address5) {
    this.address5 = address5;
  }

  public DeathscreenResult postcode(String postcode) {
    this.postcode = postcode;
    return this;
  }

   /**
   * Get postcode
   * @return postcode
  **/
  @ApiModelProperty(value = "")
  public String getPostcode() {
    return postcode;
  }

  public void setPostcode(String postcode) {
    this.postcode = postcode;
  }

  public DeathscreenResult matchType(String matchType) {
    this.matchType = matchType;
    return this;
  }

   /**
   * Get matchType
   * @return matchType
  **/
  @ApiModelProperty(value = "")
  public String getMatchType() {
    return matchType;
  }

  public void setMatchType(String matchType) {
    this.matchType = matchType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeathscreenResult deathscreenResult = (DeathscreenResult) o;
    return Objects.equals(this.forename, deathscreenResult.forename) &&
        Objects.equals(this.secondName, deathscreenResult.secondName) &&
        Objects.equals(this.thirdName, deathscreenResult.thirdName) &&
        Objects.equals(this.fourthName, deathscreenResult.fourthName) &&
        Objects.equals(this.surname, deathscreenResult.surname) &&
        Objects.equals(this.district, deathscreenResult.district) &&
        Objects.equals(this.DOB, deathscreenResult.DOB) &&
        Objects.equals(this.DOD, deathscreenResult.DOD) &&
        Objects.equals(this.DOR, deathscreenResult.DOR) &&
        Objects.equals(this.volumeNo, deathscreenResult.volumeNo) &&
        Objects.equals(this.distNo, deathscreenResult.distNo) &&
        Objects.equals(this.pageNo, deathscreenResult.pageNo) &&
        Objects.equals(this.regNo, deathscreenResult.regNo) &&
        Objects.equals(this.entryNo, deathscreenResult.entryNo) &&
        Objects.equals(this.placeOfBirth, deathscreenResult.placeOfBirth) &&
        Objects.equals(this.maidenName, deathscreenResult.maidenName) &&
        Objects.equals(this.grOReference, deathscreenResult.grOReference) &&
        Objects.equals(this.address1, deathscreenResult.address1) &&
        Objects.equals(this.address2, deathscreenResult.address2) &&
        Objects.equals(this.address3, deathscreenResult.address3) &&
        Objects.equals(this.address4, deathscreenResult.address4) &&
        Objects.equals(this.address5, deathscreenResult.address5) &&
        Objects.equals(this.postcode, deathscreenResult.postcode) &&
        Objects.equals(this.matchType, deathscreenResult.matchType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(forename, secondName, thirdName, fourthName, surname, district, DOB, DOD, DOR, volumeNo, distNo, pageNo, regNo, entryNo, placeOfBirth, maidenName, grOReference, address1, address2, address3, address4, address5, postcode, matchType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeathscreenResult {\n");
    
    sb.append("    forename: ").append(toIndentedString(forename)).append("\n");
    sb.append("    secondName: ").append(toIndentedString(secondName)).append("\n");
    sb.append("    thirdName: ").append(toIndentedString(thirdName)).append("\n");
    sb.append("    fourthName: ").append(toIndentedString(fourthName)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    district: ").append(toIndentedString(district)).append("\n");
    sb.append("    DOB: ").append(toIndentedString(DOB)).append("\n");
    sb.append("    DOD: ").append(toIndentedString(DOD)).append("\n");
    sb.append("    DOR: ").append(toIndentedString(DOR)).append("\n");
    sb.append("    volumeNo: ").append(toIndentedString(volumeNo)).append("\n");
    sb.append("    distNo: ").append(toIndentedString(distNo)).append("\n");
    sb.append("    pageNo: ").append(toIndentedString(pageNo)).append("\n");
    sb.append("    regNo: ").append(toIndentedString(regNo)).append("\n");
    sb.append("    entryNo: ").append(toIndentedString(entryNo)).append("\n");
    sb.append("    placeOfBirth: ").append(toIndentedString(placeOfBirth)).append("\n");
    sb.append("    maidenName: ").append(toIndentedString(maidenName)).append("\n");
    sb.append("    grOReference: ").append(toIndentedString(grOReference)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    address3: ").append(toIndentedString(address3)).append("\n");
    sb.append("    address4: ").append(toIndentedString(address4)).append("\n");
    sb.append("    address5: ").append(toIndentedString(address5)).append("\n");
    sb.append("    postcode: ").append(toIndentedString(postcode)).append("\n");
    sb.append("    matchType: ").append(toIndentedString(matchType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

