/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AddressData;
import io.swagger.client.model.CorporatePosition;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

/**
 * Director
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class Director {
  @SerializedName("Gender")
  private Integer gender = null;

  @SerializedName("DateOfBirth")
  private DateTime dateOfBirth = null;

  @SerializedName("DateOfBirthSpecified")
  private Boolean dateOfBirthSpecified = null;

  @SerializedName("Position")
  private List<CorporatePosition> position = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("Address")
  private AddressData address = null;

  public Director gender(Integer gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @ApiModelProperty(value = "")
  public Integer getGender() {
    return gender;
  }

  public void setGender(Integer gender) {
    this.gender = gender;
  }

  public Director dateOfBirth(DateTime dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

   /**
   * Get dateOfBirth
   * @return dateOfBirth
  **/
  @ApiModelProperty(value = "")
  public DateTime getDateOfBirth() {
    return dateOfBirth;
  }

  public void setDateOfBirth(DateTime dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public Director dateOfBirthSpecified(Boolean dateOfBirthSpecified) {
    this.dateOfBirthSpecified = dateOfBirthSpecified;
    return this;
  }

   /**
   * Get dateOfBirthSpecified
   * @return dateOfBirthSpecified
  **/
  @ApiModelProperty(value = "")
  public Boolean getDateOfBirthSpecified() {
    return dateOfBirthSpecified;
  }

  public void setDateOfBirthSpecified(Boolean dateOfBirthSpecified) {
    this.dateOfBirthSpecified = dateOfBirthSpecified;
  }

  public Director position(List<CorporatePosition> position) {
    this.position = position;
    return this;
  }

  public Director addPositionItem(CorporatePosition positionItem) {
    if (this.position == null) {
      this.position = new ArrayList<CorporatePosition>();
    }
    this.position.add(positionItem);
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(value = "")
  public List<CorporatePosition> getPosition() {
    return position;
  }

  public void setPosition(List<CorporatePosition> position) {
    this.position = position;
  }

  public Director name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Director address(AddressData address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public AddressData getAddress() {
    return address;
  }

  public void setAddress(AddressData address) {
    this.address = address;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Director director = (Director) o;
    return Objects.equals(this.gender, director.gender) &&
        Objects.equals(this.dateOfBirth, director.dateOfBirth) &&
        Objects.equals(this.dateOfBirthSpecified, director.dateOfBirthSpecified) &&
        Objects.equals(this.position, director.position) &&
        Objects.equals(this.name, director.name) &&
        Objects.equals(this.address, director.address);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gender, dateOfBirth, dateOfBirthSpecified, position, name, address);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Director {\n");
    
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    dateOfBirthSpecified: ").append(toIndentedString(dateOfBirthSpecified)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

