/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DOBPart
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class DOBPart {
  @SerializedName("TracesmartDOB")
  private Integer tracesmartDOB = null;

  @SerializedName("ExperianDOB")
  private Integer experianDOB = null;

  @SerializedName("ExperianDOBSpecified")
  private Boolean experianDOBSpecified = null;

  @SerializedName("EquifaxDOB")
  private Integer equifaxDOB = null;

  @SerializedName("EquifaxDOBSpecified")
  private Boolean equifaxDOBSpecified = null;

  @SerializedName("EquifaxDOBStatus")
  private String equifaxDOBStatus = null;

  public DOBPart tracesmartDOB(Integer tracesmartDOB) {
    this.tracesmartDOB = tracesmartDOB;
    return this;
  }

   /**
   * Get tracesmartDOB
   * @return tracesmartDOB
  **/
  @ApiModelProperty(value = "")
  public Integer getTracesmartDOB() {
    return tracesmartDOB;
  }

  public void setTracesmartDOB(Integer tracesmartDOB) {
    this.tracesmartDOB = tracesmartDOB;
  }

  public DOBPart experianDOB(Integer experianDOB) {
    this.experianDOB = experianDOB;
    return this;
  }

   /**
   * Get experianDOB
   * @return experianDOB
  **/
  @ApiModelProperty(value = "")
  public Integer getExperianDOB() {
    return experianDOB;
  }

  public void setExperianDOB(Integer experianDOB) {
    this.experianDOB = experianDOB;
  }

  public DOBPart experianDOBSpecified(Boolean experianDOBSpecified) {
    this.experianDOBSpecified = experianDOBSpecified;
    return this;
  }

   /**
   * Get experianDOBSpecified
   * @return experianDOBSpecified
  **/
  @ApiModelProperty(value = "")
  public Boolean getExperianDOBSpecified() {
    return experianDOBSpecified;
  }

  public void setExperianDOBSpecified(Boolean experianDOBSpecified) {
    this.experianDOBSpecified = experianDOBSpecified;
  }

  public DOBPart equifaxDOB(Integer equifaxDOB) {
    this.equifaxDOB = equifaxDOB;
    return this;
  }

   /**
   * Get equifaxDOB
   * @return equifaxDOB
  **/
  @ApiModelProperty(value = "")
  public Integer getEquifaxDOB() {
    return equifaxDOB;
  }

  public void setEquifaxDOB(Integer equifaxDOB) {
    this.equifaxDOB = equifaxDOB;
  }

  public DOBPart equifaxDOBSpecified(Boolean equifaxDOBSpecified) {
    this.equifaxDOBSpecified = equifaxDOBSpecified;
    return this;
  }

   /**
   * Get equifaxDOBSpecified
   * @return equifaxDOBSpecified
  **/
  @ApiModelProperty(value = "")
  public Boolean getEquifaxDOBSpecified() {
    return equifaxDOBSpecified;
  }

  public void setEquifaxDOBSpecified(Boolean equifaxDOBSpecified) {
    this.equifaxDOBSpecified = equifaxDOBSpecified;
  }

  public DOBPart equifaxDOBStatus(String equifaxDOBStatus) {
    this.equifaxDOBStatus = equifaxDOBStatus;
    return this;
  }

   /**
   * Get equifaxDOBStatus
   * @return equifaxDOBStatus
  **/
  @ApiModelProperty(value = "")
  public String getEquifaxDOBStatus() {
    return equifaxDOBStatus;
  }

  public void setEquifaxDOBStatus(String equifaxDOBStatus) {
    this.equifaxDOBStatus = equifaxDOBStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DOBPart doBPart = (DOBPart) o;
    return Objects.equals(this.tracesmartDOB, doBPart.tracesmartDOB) &&
        Objects.equals(this.experianDOB, doBPart.experianDOB) &&
        Objects.equals(this.experianDOBSpecified, doBPart.experianDOBSpecified) &&
        Objects.equals(this.equifaxDOB, doBPart.equifaxDOB) &&
        Objects.equals(this.equifaxDOBSpecified, doBPart.equifaxDOBSpecified) &&
        Objects.equals(this.equifaxDOBStatus, doBPart.equifaxDOBStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tracesmartDOB, experianDOB, experianDOBSpecified, equifaxDOB, equifaxDOBSpecified, equifaxDOBStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DOBPart {\n");
    
    sb.append("    tracesmartDOB: ").append(toIndentedString(tracesmartDOB)).append("\n");
    sb.append("    experianDOB: ").append(toIndentedString(experianDOB)).append("\n");
    sb.append("    experianDOBSpecified: ").append(toIndentedString(experianDOBSpecified)).append("\n");
    sb.append("    equifaxDOB: ").append(toIndentedString(equifaxDOB)).append("\n");
    sb.append("    equifaxDOBSpecified: ").append(toIndentedString(equifaxDOBSpecified)).append("\n");
    sb.append("    equifaxDOBStatus: ").append(toIndentedString(equifaxDOBStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

