/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EmployeeInformation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class EmployeeInformation {
  @SerializedName("Year")
  private Integer year = null;

  @SerializedName("YearSpecified")
  private Boolean yearSpecified = null;

  @SerializedName("NumberOfEmployees")
  private String numberOfEmployees = null;

  public EmployeeInformation year(Integer year) {
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @ApiModelProperty(value = "")
  public Integer getYear() {
    return year;
  }

  public void setYear(Integer year) {
    this.year = year;
  }

  public EmployeeInformation yearSpecified(Boolean yearSpecified) {
    this.yearSpecified = yearSpecified;
    return this;
  }

   /**
   * Get yearSpecified
   * @return yearSpecified
  **/
  @ApiModelProperty(value = "")
  public Boolean getYearSpecified() {
    return yearSpecified;
  }

  public void setYearSpecified(Boolean yearSpecified) {
    this.yearSpecified = yearSpecified;
  }

  public EmployeeInformation numberOfEmployees(String numberOfEmployees) {
    this.numberOfEmployees = numberOfEmployees;
    return this;
  }

   /**
   * Get numberOfEmployees
   * @return numberOfEmployees
  **/
  @ApiModelProperty(value = "")
  public String getNumberOfEmployees() {
    return numberOfEmployees;
  }

  public void setNumberOfEmployees(String numberOfEmployees) {
    this.numberOfEmployees = numberOfEmployees;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeInformation employeeInformation = (EmployeeInformation) o;
    return Objects.equals(this.year, employeeInformation.year) &&
        Objects.equals(this.yearSpecified, employeeInformation.yearSpecified) &&
        Objects.equals(this.numberOfEmployees, employeeInformation.numberOfEmployees);
  }

  @Override
  public int hashCode() {
    return Objects.hash(year, yearSpecified, numberOfEmployees);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeInformation {\n");
    
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    yearSpecified: ").append(toIndentedString(yearSpecified)).append("\n");
    sb.append("    numberOfEmployees: ").append(toIndentedString(numberOfEmployees)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

