/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AddressLabel;
import java.io.IOException;

/**
 * InsolvencyResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class InsolvencyResult {
  @SerializedName("Type")
  private String type = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("CaseNo")
  private String caseNo = null;

  @SerializedName("Address")
  private AddressLabel address = null;

  @SerializedName("DOB")
  private String DOB = null;

  @SerializedName("Court")
  private String court = null;

  @SerializedName("StartDate")
  private String startDate = null;

  @SerializedName("Status")
  private String status = null;

  @SerializedName("Occupation")
  private String occupation = null;

  @SerializedName("Aliases")
  private String aliases = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("ServiceOffice")
  private String serviceOffice = null;

  @SerializedName("TelephoneNumber")
  private String telephoneNumber = null;

  @SerializedName("CaseType")
  private String caseType = null;

  @SerializedName("TradingNames")
  private String tradingNames = null;

  @SerializedName("DebtTotal")
  private String debtTotal = null;

  @SerializedName("AssetTotal")
  private String assetTotal = null;

  @SerializedName("PreviousAddress")
  private AddressLabel previousAddress = null;

  @SerializedName("PresentationDate")
  private String presentationDate = null;

  public InsolvencyResult type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public InsolvencyResult name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public InsolvencyResult caseNo(String caseNo) {
    this.caseNo = caseNo;
    return this;
  }

   /**
   * Get caseNo
   * @return caseNo
  **/
  @ApiModelProperty(value = "")
  public String getCaseNo() {
    return caseNo;
  }

  public void setCaseNo(String caseNo) {
    this.caseNo = caseNo;
  }

  public InsolvencyResult address(AddressLabel address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public AddressLabel getAddress() {
    return address;
  }

  public void setAddress(AddressLabel address) {
    this.address = address;
  }

  public InsolvencyResult DOB(String DOB) {
    this.DOB = DOB;
    return this;
  }

   /**
   * Get DOB
   * @return DOB
  **/
  @ApiModelProperty(value = "")
  public String getDOB() {
    return DOB;
  }

  public void setDOB(String DOB) {
    this.DOB = DOB;
  }

  public InsolvencyResult court(String court) {
    this.court = court;
    return this;
  }

   /**
   * Get court
   * @return court
  **/
  @ApiModelProperty(value = "")
  public String getCourt() {
    return court;
  }

  public void setCourt(String court) {
    this.court = court;
  }

  public InsolvencyResult startDate(String startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  @ApiModelProperty(value = "")
  public String getStartDate() {
    return startDate;
  }

  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }

  public InsolvencyResult status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public InsolvencyResult occupation(String occupation) {
    this.occupation = occupation;
    return this;
  }

   /**
   * Get occupation
   * @return occupation
  **/
  @ApiModelProperty(value = "")
  public String getOccupation() {
    return occupation;
  }

  public void setOccupation(String occupation) {
    this.occupation = occupation;
  }

  public InsolvencyResult aliases(String aliases) {
    this.aliases = aliases;
    return this;
  }

   /**
   * Get aliases
   * @return aliases
  **/
  @ApiModelProperty(value = "")
  public String getAliases() {
    return aliases;
  }

  public void setAliases(String aliases) {
    this.aliases = aliases;
  }

  public InsolvencyResult description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public InsolvencyResult serviceOffice(String serviceOffice) {
    this.serviceOffice = serviceOffice;
    return this;
  }

   /**
   * Get serviceOffice
   * @return serviceOffice
  **/
  @ApiModelProperty(value = "")
  public String getServiceOffice() {
    return serviceOffice;
  }

  public void setServiceOffice(String serviceOffice) {
    this.serviceOffice = serviceOffice;
  }

  public InsolvencyResult telephoneNumber(String telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
    return this;
  }

   /**
   * Get telephoneNumber
   * @return telephoneNumber
  **/
  @ApiModelProperty(value = "")
  public String getTelephoneNumber() {
    return telephoneNumber;
  }

  public void setTelephoneNumber(String telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
  }

  public InsolvencyResult caseType(String caseType) {
    this.caseType = caseType;
    return this;
  }

   /**
   * Get caseType
   * @return caseType
  **/
  @ApiModelProperty(value = "")
  public String getCaseType() {
    return caseType;
  }

  public void setCaseType(String caseType) {
    this.caseType = caseType;
  }

  public InsolvencyResult tradingNames(String tradingNames) {
    this.tradingNames = tradingNames;
    return this;
  }

   /**
   * Get tradingNames
   * @return tradingNames
  **/
  @ApiModelProperty(value = "")
  public String getTradingNames() {
    return tradingNames;
  }

  public void setTradingNames(String tradingNames) {
    this.tradingNames = tradingNames;
  }

  public InsolvencyResult debtTotal(String debtTotal) {
    this.debtTotal = debtTotal;
    return this;
  }

   /**
   * Get debtTotal
   * @return debtTotal
  **/
  @ApiModelProperty(value = "")
  public String getDebtTotal() {
    return debtTotal;
  }

  public void setDebtTotal(String debtTotal) {
    this.debtTotal = debtTotal;
  }

  public InsolvencyResult assetTotal(String assetTotal) {
    this.assetTotal = assetTotal;
    return this;
  }

   /**
   * Get assetTotal
   * @return assetTotal
  **/
  @ApiModelProperty(value = "")
  public String getAssetTotal() {
    return assetTotal;
  }

  public void setAssetTotal(String assetTotal) {
    this.assetTotal = assetTotal;
  }

  public InsolvencyResult previousAddress(AddressLabel previousAddress) {
    this.previousAddress = previousAddress;
    return this;
  }

   /**
   * Get previousAddress
   * @return previousAddress
  **/
  @ApiModelProperty(value = "")
  public AddressLabel getPreviousAddress() {
    return previousAddress;
  }

  public void setPreviousAddress(AddressLabel previousAddress) {
    this.previousAddress = previousAddress;
  }

  public InsolvencyResult presentationDate(String presentationDate) {
    this.presentationDate = presentationDate;
    return this;
  }

   /**
   * Get presentationDate
   * @return presentationDate
  **/
  @ApiModelProperty(value = "")
  public String getPresentationDate() {
    return presentationDate;
  }

  public void setPresentationDate(String presentationDate) {
    this.presentationDate = presentationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InsolvencyResult insolvencyResult = (InsolvencyResult) o;
    return Objects.equals(this.type, insolvencyResult.type) &&
        Objects.equals(this.name, insolvencyResult.name) &&
        Objects.equals(this.caseNo, insolvencyResult.caseNo) &&
        Objects.equals(this.address, insolvencyResult.address) &&
        Objects.equals(this.DOB, insolvencyResult.DOB) &&
        Objects.equals(this.court, insolvencyResult.court) &&
        Objects.equals(this.startDate, insolvencyResult.startDate) &&
        Objects.equals(this.status, insolvencyResult.status) &&
        Objects.equals(this.occupation, insolvencyResult.occupation) &&
        Objects.equals(this.aliases, insolvencyResult.aliases) &&
        Objects.equals(this.description, insolvencyResult.description) &&
        Objects.equals(this.serviceOffice, insolvencyResult.serviceOffice) &&
        Objects.equals(this.telephoneNumber, insolvencyResult.telephoneNumber) &&
        Objects.equals(this.caseType, insolvencyResult.caseType) &&
        Objects.equals(this.tradingNames, insolvencyResult.tradingNames) &&
        Objects.equals(this.debtTotal, insolvencyResult.debtTotal) &&
        Objects.equals(this.assetTotal, insolvencyResult.assetTotal) &&
        Objects.equals(this.previousAddress, insolvencyResult.previousAddress) &&
        Objects.equals(this.presentationDate, insolvencyResult.presentationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, name, caseNo, address, DOB, court, startDate, status, occupation, aliases, description, serviceOffice, telephoneNumber, caseType, tradingNames, debtTotal, assetTotal, previousAddress, presentationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InsolvencyResult {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    caseNo: ").append(toIndentedString(caseNo)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    DOB: ").append(toIndentedString(DOB)).append("\n");
    sb.append("    court: ").append(toIndentedString(court)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    occupation: ").append(toIndentedString(occupation)).append("\n");
    sb.append("    aliases: ").append(toIndentedString(aliases)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    serviceOffice: ").append(toIndentedString(serviceOffice)).append("\n");
    sb.append("    telephoneNumber: ").append(toIndentedString(telephoneNumber)).append("\n");
    sb.append("    caseType: ").append(toIndentedString(caseType)).append("\n");
    sb.append("    tradingNames: ").append(toIndentedString(tradingNames)).append("\n");
    sb.append("    debtTotal: ").append(toIndentedString(debtTotal)).append("\n");
    sb.append("    assetTotal: ").append(toIndentedString(assetTotal)).append("\n");
    sb.append("    previousAddress: ").append(toIndentedString(previousAddress)).append("\n");
    sb.append("    presentationDate: ").append(toIndentedString(presentationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

