/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.LawyerTO;
import java.io.IOException;

/**
 * LawyerCheckApplicationTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class LawyerCheckApplicationTO {
  @SerializedName("lawyerApplicant")
  private LawyerTO lawyerApplicant = null;

  @SerializedName("reference")
  private String reference = null;

  public LawyerCheckApplicationTO lawyerApplicant(LawyerTO lawyerApplicant) {
    this.lawyerApplicant = lawyerApplicant;
    return this;
  }

   /**
   * Get lawyerApplicant
   * @return lawyerApplicant
  **/
  @ApiModelProperty(required = true, value = "")
  public LawyerTO getLawyerApplicant() {
    return lawyerApplicant;
  }

  public void setLawyerApplicant(LawyerTO lawyerApplicant) {
    this.lawyerApplicant = lawyerApplicant;
  }

  public LawyerCheckApplicationTO reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(required = true, value = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LawyerCheckApplicationTO lawyerCheckApplicationTO = (LawyerCheckApplicationTO) o;
    return Objects.equals(this.lawyerApplicant, lawyerCheckApplicationTO.lawyerApplicant) &&
        Objects.equals(this.reference, lawyerCheckApplicationTO.reference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lawyerApplicant, reference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LawyerCheckApplicationTO {\n");
    
    sb.append("    lawyerApplicant: ").append(toIndentedString(lawyerApplicant)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

