/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * LawyerTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class LawyerTO {
  @SerializedName("PDFEmail")
  private String pdFEmail = null;

  @SerializedName("account")
  private String account = null;

  @SerializedName("applicationNumber")
  private String applicationNumber = null;

  @SerializedName("bespokeReference")
  private String bespokeReference = null;

  @SerializedName("bespokeReference2")
  private String bespokeReference2 = null;

  @SerializedName("companyName")
  private String companyName = null;

  @SerializedName("conveyancerPracticeName")
  private String conveyancerPracticeName = null;

  @SerializedName("feeEarner")
  private String feeEarner = null;

  @SerializedName("informLender")
  private Boolean informLender = null;

  @SerializedName("lenderName")
  private String lenderName = null;

  @SerializedName("postCode")
  private String postCode = null;

  @SerializedName("proposedCompletionDate")
  private DateTime proposedCompletionDate = null;

  @SerializedName("regBodyNumber")
  private String regBodyNumber = null;

  @SerializedName("sortCode")
  private String sortCode = null;

  public LawyerTO pdFEmail(String pdFEmail) {
    this.pdFEmail = pdFEmail;
    return this;
  }

   /**
   * Get pdFEmail
   * @return pdFEmail
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPdFEmail() {
    return pdFEmail;
  }

  public void setPdFEmail(String pdFEmail) {
    this.pdFEmail = pdFEmail;
  }

  public LawyerTO account(String account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public LawyerTO applicationNumber(String applicationNumber) {
    this.applicationNumber = applicationNumber;
    return this;
  }

   /**
   * Get applicationNumber
   * @return applicationNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public String getApplicationNumber() {
    return applicationNumber;
  }

  public void setApplicationNumber(String applicationNumber) {
    this.applicationNumber = applicationNumber;
  }

  public LawyerTO bespokeReference(String bespokeReference) {
    this.bespokeReference = bespokeReference;
    return this;
  }

   /**
   * Get bespokeReference
   * @return bespokeReference
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBespokeReference() {
    return bespokeReference;
  }

  public void setBespokeReference(String bespokeReference) {
    this.bespokeReference = bespokeReference;
  }

  public LawyerTO bespokeReference2(String bespokeReference2) {
    this.bespokeReference2 = bespokeReference2;
    return this;
  }

   /**
   * Get bespokeReference2
   * @return bespokeReference2
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBespokeReference2() {
    return bespokeReference2;
  }

  public void setBespokeReference2(String bespokeReference2) {
    this.bespokeReference2 = bespokeReference2;
  }

  public LawyerTO companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Get companyName
   * @return companyName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public LawyerTO conveyancerPracticeName(String conveyancerPracticeName) {
    this.conveyancerPracticeName = conveyancerPracticeName;
    return this;
  }

   /**
   * Get conveyancerPracticeName
   * @return conveyancerPracticeName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getConveyancerPracticeName() {
    return conveyancerPracticeName;
  }

  public void setConveyancerPracticeName(String conveyancerPracticeName) {
    this.conveyancerPracticeName = conveyancerPracticeName;
  }

  public LawyerTO feeEarner(String feeEarner) {
    this.feeEarner = feeEarner;
    return this;
  }

   /**
   * Get feeEarner
   * @return feeEarner
  **/
  @ApiModelProperty(required = true, value = "")
  public String getFeeEarner() {
    return feeEarner;
  }

  public void setFeeEarner(String feeEarner) {
    this.feeEarner = feeEarner;
  }

  public LawyerTO informLender(Boolean informLender) {
    this.informLender = informLender;
    return this;
  }

   /**
   * Get informLender
   * @return informLender
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getInformLender() {
    return informLender;
  }

  public void setInformLender(Boolean informLender) {
    this.informLender = informLender;
  }

  public LawyerTO lenderName(String lenderName) {
    this.lenderName = lenderName;
    return this;
  }

   /**
   * Get lenderName
   * @return lenderName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLenderName() {
    return lenderName;
  }

  public void setLenderName(String lenderName) {
    this.lenderName = lenderName;
  }

  public LawyerTO postCode(String postCode) {
    this.postCode = postCode;
    return this;
  }

   /**
   * Get postCode
   * @return postCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPostCode() {
    return postCode;
  }

  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }

  public LawyerTO proposedCompletionDate(DateTime proposedCompletionDate) {
    this.proposedCompletionDate = proposedCompletionDate;
    return this;
  }

   /**
   * Get proposedCompletionDate
   * @return proposedCompletionDate
  **/
  @ApiModelProperty(required = true, value = "")
  public DateTime getProposedCompletionDate() {
    return proposedCompletionDate;
  }

  public void setProposedCompletionDate(DateTime proposedCompletionDate) {
    this.proposedCompletionDate = proposedCompletionDate;
  }

  public LawyerTO regBodyNumber(String regBodyNumber) {
    this.regBodyNumber = regBodyNumber;
    return this;
  }

   /**
   * Get regBodyNumber
   * @return regBodyNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public String getRegBodyNumber() {
    return regBodyNumber;
  }

  public void setRegBodyNumber(String regBodyNumber) {
    this.regBodyNumber = regBodyNumber;
  }

  public LawyerTO sortCode(String sortCode) {
    this.sortCode = sortCode;
    return this;
  }

   /**
   * Get sortCode
   * @return sortCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getSortCode() {
    return sortCode;
  }

  public void setSortCode(String sortCode) {
    this.sortCode = sortCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LawyerTO lawyerTO = (LawyerTO) o;
    return Objects.equals(this.pdFEmail, lawyerTO.pdFEmail) &&
        Objects.equals(this.account, lawyerTO.account) &&
        Objects.equals(this.applicationNumber, lawyerTO.applicationNumber) &&
        Objects.equals(this.bespokeReference, lawyerTO.bespokeReference) &&
        Objects.equals(this.bespokeReference2, lawyerTO.bespokeReference2) &&
        Objects.equals(this.companyName, lawyerTO.companyName) &&
        Objects.equals(this.conveyancerPracticeName, lawyerTO.conveyancerPracticeName) &&
        Objects.equals(this.feeEarner, lawyerTO.feeEarner) &&
        Objects.equals(this.informLender, lawyerTO.informLender) &&
        Objects.equals(this.lenderName, lawyerTO.lenderName) &&
        Objects.equals(this.postCode, lawyerTO.postCode) &&
        Objects.equals(this.proposedCompletionDate, lawyerTO.proposedCompletionDate) &&
        Objects.equals(this.regBodyNumber, lawyerTO.regBodyNumber) &&
        Objects.equals(this.sortCode, lawyerTO.sortCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pdFEmail, account, applicationNumber, bespokeReference, bespokeReference2, companyName, conveyancerPracticeName, feeEarner, informLender, lenderName, postCode, proposedCompletionDate, regBodyNumber, sortCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LawyerTO {\n");
    
    sb.append("    pdFEmail: ").append(toIndentedString(pdFEmail)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    applicationNumber: ").append(toIndentedString(applicationNumber)).append("\n");
    sb.append("    bespokeReference: ").append(toIndentedString(bespokeReference)).append("\n");
    sb.append("    bespokeReference2: ").append(toIndentedString(bespokeReference2)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    conveyancerPracticeName: ").append(toIndentedString(conveyancerPracticeName)).append("\n");
    sb.append("    feeEarner: ").append(toIndentedString(feeEarner)).append("\n");
    sb.append("    informLender: ").append(toIndentedString(informLender)).append("\n");
    sb.append("    lenderName: ").append(toIndentedString(lenderName)).append("\n");
    sb.append("    postCode: ").append(toIndentedString(postCode)).append("\n");
    sb.append("    proposedCompletionDate: ").append(toIndentedString(proposedCompletionDate)).append("\n");
    sb.append("    regBodyNumber: ").append(toIndentedString(regBodyNumber)).append("\n");
    sb.append("    sortCode: ").append(toIndentedString(sortCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

