/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LtdCompanyFullReportAdditionalInformation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class LtdCompanyFullReportAdditionalInformation {
  @SerializedName("Any")
  private List<List<Object>> any = null;

  @SerializedName("AnyAttr")
  private List<List<Object>> anyAttr = null;

  public LtdCompanyFullReportAdditionalInformation any(List<List<Object>> any) {
    this.any = any;
    return this;
  }

  public LtdCompanyFullReportAdditionalInformation addAnyItem(List<Object> anyItem) {
    if (this.any == null) {
      this.any = new ArrayList<List<Object>>();
    }
    this.any.add(anyItem);
    return this;
  }

   /**
   * Get any
   * @return any
  **/
  @ApiModelProperty(value = "")
  public List<List<Object>> getAny() {
    return any;
  }

  public void setAny(List<List<Object>> any) {
    this.any = any;
  }

  public LtdCompanyFullReportAdditionalInformation anyAttr(List<List<Object>> anyAttr) {
    this.anyAttr = anyAttr;
    return this;
  }

  public LtdCompanyFullReportAdditionalInformation addAnyAttrItem(List<Object> anyAttrItem) {
    if (this.anyAttr == null) {
      this.anyAttr = new ArrayList<List<Object>>();
    }
    this.anyAttr.add(anyAttrItem);
    return this;
  }

   /**
   * Get anyAttr
   * @return anyAttr
  **/
  @ApiModelProperty(value = "")
  public List<List<Object>> getAnyAttr() {
    return anyAttr;
  }

  public void setAnyAttr(List<List<Object>> anyAttr) {
    this.anyAttr = anyAttr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LtdCompanyFullReportAdditionalInformation ltdCompanyFullReportAdditionalInformation = (LtdCompanyFullReportAdditionalInformation) o;
    return Objects.equals(this.any, ltdCompanyFullReportAdditionalInformation.any) &&
        Objects.equals(this.anyAttr, ltdCompanyFullReportAdditionalInformation.anyAttr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(any, anyAttr);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LtdCompanyFullReportAdditionalInformation {\n");
    
    sb.append("    any: ").append(toIndentedString(any)).append("\n");
    sb.append("    anyAttr: ").append(toIndentedString(anyAttr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

