/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CreditRating;
import io.swagger.client.model.FinancialValueDecimal;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * LtdCreditScore
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class LtdCreditScore {
  @SerializedName("CurrentCreditRating")
  private CreditRating currentCreditRating = null;

  @SerializedName("CurrentContractLimit")
  private FinancialValueDecimal currentContractLimit = null;

  @SerializedName("PreviousCreditRating")
  private CreditRating previousCreditRating = null;

  @SerializedName("DateOfLatestRatingChange")
  private DateTime dateOfLatestRatingChange = null;

  @SerializedName("DateOfLatestRatingChangeSpecified")
  private Boolean dateOfLatestRatingChangeSpecified = null;

  public LtdCreditScore currentCreditRating(CreditRating currentCreditRating) {
    this.currentCreditRating = currentCreditRating;
    return this;
  }

   /**
   * Get currentCreditRating
   * @return currentCreditRating
  **/
  @ApiModelProperty(value = "")
  public CreditRating getCurrentCreditRating() {
    return currentCreditRating;
  }

  public void setCurrentCreditRating(CreditRating currentCreditRating) {
    this.currentCreditRating = currentCreditRating;
  }

  public LtdCreditScore currentContractLimit(FinancialValueDecimal currentContractLimit) {
    this.currentContractLimit = currentContractLimit;
    return this;
  }

   /**
   * Get currentContractLimit
   * @return currentContractLimit
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getCurrentContractLimit() {
    return currentContractLimit;
  }

  public void setCurrentContractLimit(FinancialValueDecimal currentContractLimit) {
    this.currentContractLimit = currentContractLimit;
  }

  public LtdCreditScore previousCreditRating(CreditRating previousCreditRating) {
    this.previousCreditRating = previousCreditRating;
    return this;
  }

   /**
   * Get previousCreditRating
   * @return previousCreditRating
  **/
  @ApiModelProperty(value = "")
  public CreditRating getPreviousCreditRating() {
    return previousCreditRating;
  }

  public void setPreviousCreditRating(CreditRating previousCreditRating) {
    this.previousCreditRating = previousCreditRating;
  }

  public LtdCreditScore dateOfLatestRatingChange(DateTime dateOfLatestRatingChange) {
    this.dateOfLatestRatingChange = dateOfLatestRatingChange;
    return this;
  }

   /**
   * Get dateOfLatestRatingChange
   * @return dateOfLatestRatingChange
  **/
  @ApiModelProperty(value = "")
  public DateTime getDateOfLatestRatingChange() {
    return dateOfLatestRatingChange;
  }

  public void setDateOfLatestRatingChange(DateTime dateOfLatestRatingChange) {
    this.dateOfLatestRatingChange = dateOfLatestRatingChange;
  }

  public LtdCreditScore dateOfLatestRatingChangeSpecified(Boolean dateOfLatestRatingChangeSpecified) {
    this.dateOfLatestRatingChangeSpecified = dateOfLatestRatingChangeSpecified;
    return this;
  }

   /**
   * Get dateOfLatestRatingChangeSpecified
   * @return dateOfLatestRatingChangeSpecified
  **/
  @ApiModelProperty(value = "")
  public Boolean getDateOfLatestRatingChangeSpecified() {
    return dateOfLatestRatingChangeSpecified;
  }

  public void setDateOfLatestRatingChangeSpecified(Boolean dateOfLatestRatingChangeSpecified) {
    this.dateOfLatestRatingChangeSpecified = dateOfLatestRatingChangeSpecified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LtdCreditScore ltdCreditScore = (LtdCreditScore) o;
    return Objects.equals(this.currentCreditRating, ltdCreditScore.currentCreditRating) &&
        Objects.equals(this.currentContractLimit, ltdCreditScore.currentContractLimit) &&
        Objects.equals(this.previousCreditRating, ltdCreditScore.previousCreditRating) &&
        Objects.equals(this.dateOfLatestRatingChange, ltdCreditScore.dateOfLatestRatingChange) &&
        Objects.equals(this.dateOfLatestRatingChangeSpecified, ltdCreditScore.dateOfLatestRatingChangeSpecified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currentCreditRating, currentContractLimit, previousCreditRating, dateOfLatestRatingChange, dateOfLatestRatingChangeSpecified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LtdCreditScore {\n");
    
    sb.append("    currentCreditRating: ").append(toIndentedString(currentCreditRating)).append("\n");
    sb.append("    currentContractLimit: ").append(toIndentedString(currentContractLimit)).append("\n");
    sb.append("    previousCreditRating: ").append(toIndentedString(previousCreditRating)).append("\n");
    sb.append("    dateOfLatestRatingChange: ").append(toIndentedString(dateOfLatestRatingChange)).append("\n");
    sb.append("    dateOfLatestRatingChangeSpecified: ").append(toIndentedString(dateOfLatestRatingChangeSpecified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

