/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CompanyActivity;
import io.swagger.client.model.CompanyStatusDescription;
import io.swagger.client.model.CreditRating;
import io.swagger.client.model.FinancialValueDecimal;
import java.io.IOException;

/**
 * LtdCompanySummary
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class LtdCompanySummary {
  @SerializedName("BusinessName")
  private String businessName = null;

  /**
   * Gets or Sets country
   */
  @JsonAdapter(CountryEnum.Adapter.class)
  public enum CountryEnum {
    AF("AF"),
    
    AX("AX"),
    
    AL("AL"),
    
    DZ("DZ"),
    
    AS("AS"),
    
    AD("AD"),
    
    AO("AO"),
    
    AI("AI"),
    
    AQ("AQ"),
    
    AG("AG"),
    
    AR("AR"),
    
    AM("AM"),
    
    AW("AW"),
    
    AU("AU"),
    
    AT("AT"),
    
    AZ("AZ"),
    
    BS("BS"),
    
    BH("BH"),
    
    BD("BD"),
    
    BB("BB"),
    
    BY("BY"),
    
    BE("BE"),
    
    BZ("BZ"),
    
    BJ("BJ"),
    
    BM("BM"),
    
    BT("BT"),
    
    BO("BO"),
    
    BA("BA"),
    
    BW("BW"),
    
    BV("BV"),
    
    BR("BR"),
    
    IO("IO"),
    
    BN("BN"),
    
    BG("BG"),
    
    BF("BF"),
    
    BI("BI"),
    
    KH("KH"),
    
    CM("CM"),
    
    CA("CA"),
    
    CV("CV"),
    
    KY("KY"),
    
    CF("CF"),
    
    TD("TD"),
    
    CL("CL"),
    
    CN("CN"),
    
    CX("CX"),
    
    CC("CC"),
    
    CO("CO"),
    
    KM("KM"),
    
    CG("CG"),
    
    CD("CD"),
    
    CK("CK"),
    
    CR("CR"),
    
    CI("CI"),
    
    HR("HR"),
    
    CU("CU"),
    
    CY("CY"),
    
    CZ("CZ"),
    
    DK("DK"),
    
    DJ("DJ"),
    
    DM("DM"),
    
    DO("DO"),
    
    EC("EC"),
    
    EG("EG"),
    
    SV("SV"),
    
    GQ("GQ"),
    
    ER("ER"),
    
    EE("EE"),
    
    ET("ET"),
    
    FK("FK"),
    
    FO("FO"),
    
    FJ("FJ"),
    
    FI("FI"),
    
    FR("FR"),
    
    GF("GF"),
    
    PF("PF"),
    
    TF("TF"),
    
    GA("GA"),
    
    GM("GM"),
    
    GE("GE"),
    
    DE("DE"),
    
    GH("GH"),
    
    GI("GI"),
    
    GR("GR"),
    
    GL("GL"),
    
    GD("GD"),
    
    GP("GP"),
    
    GU("GU"),
    
    GT("GT"),
    
    GG("GG"),
    
    GN("GN"),
    
    GW("GW"),
    
    GY("GY"),
    
    HT("HT"),
    
    HM("HM"),
    
    HN("HN"),
    
    HK("HK"),
    
    HU("HU"),
    
    IS("IS"),
    
    IN("IN"),
    
    ID("ID"),
    
    IR("IR"),
    
    IQ("IQ"),
    
    IE("IE"),
    
    IM("IM"),
    
    IL("IL"),
    
    IT("IT"),
    
    JM("JM"),
    
    JP("JP"),
    
    JE("JE"),
    
    JO("JO"),
    
    KZ("KZ"),
    
    KE("KE"),
    
    KI("KI"),
    
    KP("KP"),
    
    KR("KR"),
    
    KW("KW"),
    
    KG("KG"),
    
    LA("LA"),
    
    LV("LV"),
    
    LB("LB"),
    
    LS("LS"),
    
    LR("LR"),
    
    LY("LY"),
    
    LI("LI"),
    
    LT("LT"),
    
    LU("LU"),
    
    MO("MO"),
    
    MK("MK"),
    
    MG("MG"),
    
    MW("MW"),
    
    MY("MY"),
    
    MV("MV"),
    
    ML("ML"),
    
    MT("MT"),
    
    MH("MH"),
    
    MQ("MQ"),
    
    MR("MR"),
    
    MU("MU"),
    
    YT("YT"),
    
    MX("MX"),
    
    FM("FM"),
    
    MD("MD"),
    
    MC("MC"),
    
    MN("MN"),
    
    ME("ME"),
    
    MS("MS"),
    
    MA("MA"),
    
    MZ("MZ"),
    
    MM("MM"),
    
    NA("NA"),
    
    NR("NR"),
    
    NP("NP"),
    
    NL("NL"),
    
    AN("AN"),
    
    NC("NC"),
    
    NZ("NZ"),
    
    NI("NI"),
    
    NE("NE"),
    
    NG("NG"),
    
    NU("NU"),
    
    NF("NF"),
    
    MP("MP"),
    
    NO("NO"),
    
    OM("OM"),
    
    PK("PK"),
    
    PW("PW"),
    
    PS("PS"),
    
    PA("PA"),
    
    PG("PG"),
    
    PY("PY"),
    
    PE("PE"),
    
    PH("PH"),
    
    PN("PN"),
    
    PL("PL"),
    
    PT("PT"),
    
    PR("PR"),
    
    QA("QA"),
    
    RE("RE"),
    
    RO("RO"),
    
    RU("RU"),
    
    RW("RW"),
    
    BL("BL"),
    
    SH("SH"),
    
    KN("KN"),
    
    LC("LC"),
    
    MF("MF"),
    
    PM("PM"),
    
    VC("VC"),
    
    WS("WS"),
    
    SM("SM"),
    
    ST("ST"),
    
    SA("SA"),
    
    SN("SN"),
    
    RS("RS"),
    
    SC("SC"),
    
    SL("SL"),
    
    SG("SG"),
    
    SK("SK"),
    
    SI("SI"),
    
    SB("SB"),
    
    SO("SO"),
    
    ZA("ZA"),
    
    GS("GS"),
    
    ES("ES"),
    
    LK("LK"),
    
    SD("SD"),
    
    SR("SR"),
    
    SJ("SJ"),
    
    SZ("SZ"),
    
    SE("SE"),
    
    CH("CH"),
    
    SY("SY"),
    
    TW("TW"),
    
    TJ("TJ"),
    
    TZ("TZ"),
    
    TH("TH"),
    
    TL("TL"),
    
    TG("TG"),
    
    TK("TK"),
    
    TO("TO"),
    
    TT("TT"),
    
    TN("TN"),
    
    TR("TR"),
    
    TM("TM"),
    
    TC("TC"),
    
    TV("TV"),
    
    UG("UG"),
    
    UA("UA"),
    
    AE("AE"),
    
    GB("GB"),
    
    US("US"),
    
    UM("UM"),
    
    UY("UY"),
    
    UZ("UZ"),
    
    VU("VU"),
    
    VA("VA"),
    
    VE("VE"),
    
    VN("VN"),
    
    VG("VG"),
    
    VI("VI"),
    
    WF("WF"),
    
    EH("EH"),
    
    YE("YE"),
    
    ZM("ZM"),
    
    ZW("ZW"),
    
    PLC("PLC");

    private String value;

    CountryEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CountryEnum fromValue(String text) {
      for (CountryEnum b : CountryEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<CountryEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CountryEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CountryEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return CountryEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("Country")
  private CountryEnum country = null;

  @SerializedName("Number")
  private String number = null;

  @SerializedName("CompanyRegistrationNumber")
  private String companyRegistrationNumber = null;

  @SerializedName("MainActivity")
  private CompanyActivity mainActivity = null;

  @SerializedName("CompanyStatus")
  private CompanyStatusDescription companyStatus = null;

  @SerializedName("LatestTurnoverFigure")
  private FinancialValueDecimal latestTurnoverFigure = null;

  @SerializedName("LatestShareholdersEquityFigure")
  private FinancialValueDecimal latestShareholdersEquityFigure = null;

  @SerializedName("CreditRating")
  private CreditRating creditRating = null;

  public LtdCompanySummary businessName(String businessName) {
    this.businessName = businessName;
    return this;
  }

   /**
   * Get businessName
   * @return businessName
  **/
  @ApiModelProperty(value = "")
  public String getBusinessName() {
    return businessName;
  }

  public void setBusinessName(String businessName) {
    this.businessName = businessName;
  }

  public LtdCompanySummary country(CountryEnum country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public CountryEnum getCountry() {
    return country;
  }

  public void setCountry(CountryEnum country) {
    this.country = country;
  }

  public LtdCompanySummary number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @ApiModelProperty(value = "")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public LtdCompanySummary companyRegistrationNumber(String companyRegistrationNumber) {
    this.companyRegistrationNumber = companyRegistrationNumber;
    return this;
  }

   /**
   * Get companyRegistrationNumber
   * @return companyRegistrationNumber
  **/
  @ApiModelProperty(value = "")
  public String getCompanyRegistrationNumber() {
    return companyRegistrationNumber;
  }

  public void setCompanyRegistrationNumber(String companyRegistrationNumber) {
    this.companyRegistrationNumber = companyRegistrationNumber;
  }

  public LtdCompanySummary mainActivity(CompanyActivity mainActivity) {
    this.mainActivity = mainActivity;
    return this;
  }

   /**
   * Get mainActivity
   * @return mainActivity
  **/
  @ApiModelProperty(value = "")
  public CompanyActivity getMainActivity() {
    return mainActivity;
  }

  public void setMainActivity(CompanyActivity mainActivity) {
    this.mainActivity = mainActivity;
  }

  public LtdCompanySummary companyStatus(CompanyStatusDescription companyStatus) {
    this.companyStatus = companyStatus;
    return this;
  }

   /**
   * Get companyStatus
   * @return companyStatus
  **/
  @ApiModelProperty(value = "")
  public CompanyStatusDescription getCompanyStatus() {
    return companyStatus;
  }

  public void setCompanyStatus(CompanyStatusDescription companyStatus) {
    this.companyStatus = companyStatus;
  }

  public LtdCompanySummary latestTurnoverFigure(FinancialValueDecimal latestTurnoverFigure) {
    this.latestTurnoverFigure = latestTurnoverFigure;
    return this;
  }

   /**
   * Get latestTurnoverFigure
   * @return latestTurnoverFigure
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getLatestTurnoverFigure() {
    return latestTurnoverFigure;
  }

  public void setLatestTurnoverFigure(FinancialValueDecimal latestTurnoverFigure) {
    this.latestTurnoverFigure = latestTurnoverFigure;
  }

  public LtdCompanySummary latestShareholdersEquityFigure(FinancialValueDecimal latestShareholdersEquityFigure) {
    this.latestShareholdersEquityFigure = latestShareholdersEquityFigure;
    return this;
  }

   /**
   * Get latestShareholdersEquityFigure
   * @return latestShareholdersEquityFigure
  **/
  @ApiModelProperty(value = "")
  public FinancialValueDecimal getLatestShareholdersEquityFigure() {
    return latestShareholdersEquityFigure;
  }

  public void setLatestShareholdersEquityFigure(FinancialValueDecimal latestShareholdersEquityFigure) {
    this.latestShareholdersEquityFigure = latestShareholdersEquityFigure;
  }

  public LtdCompanySummary creditRating(CreditRating creditRating) {
    this.creditRating = creditRating;
    return this;
  }

   /**
   * Get creditRating
   * @return creditRating
  **/
  @ApiModelProperty(value = "")
  public CreditRating getCreditRating() {
    return creditRating;
  }

  public void setCreditRating(CreditRating creditRating) {
    this.creditRating = creditRating;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LtdCompanySummary ltdCompanySummary = (LtdCompanySummary) o;
    return Objects.equals(this.businessName, ltdCompanySummary.businessName) &&
        Objects.equals(this.country, ltdCompanySummary.country) &&
        Objects.equals(this.number, ltdCompanySummary.number) &&
        Objects.equals(this.companyRegistrationNumber, ltdCompanySummary.companyRegistrationNumber) &&
        Objects.equals(this.mainActivity, ltdCompanySummary.mainActivity) &&
        Objects.equals(this.companyStatus, ltdCompanySummary.companyStatus) &&
        Objects.equals(this.latestTurnoverFigure, ltdCompanySummary.latestTurnoverFigure) &&
        Objects.equals(this.latestShareholdersEquityFigure, ltdCompanySummary.latestShareholdersEquityFigure) &&
        Objects.equals(this.creditRating, ltdCompanySummary.creditRating);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessName, country, number, companyRegistrationNumber, mainActivity, companyStatus, latestTurnoverFigure, latestShareholdersEquityFigure, creditRating);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LtdCompanySummary {\n");
    
    sb.append("    businessName: ").append(toIndentedString(businessName)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    companyRegistrationNumber: ").append(toIndentedString(companyRegistrationNumber)).append("\n");
    sb.append("    mainActivity: ").append(toIndentedString(mainActivity)).append("\n");
    sb.append("    companyStatus: ").append(toIndentedString(companyStatus)).append("\n");
    sb.append("    latestTurnoverFigure: ").append(toIndentedString(latestTurnoverFigure)).append("\n");
    sb.append("    latestShareholdersEquityFigure: ").append(toIndentedString(latestShareholdersEquityFigure)).append("\n");
    sb.append("    creditRating: ").append(toIndentedString(creditRating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

