/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CompanyData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * LtdGroupStructure
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class LtdGroupStructure {
  @SerializedName("UltimateParent")
  private CompanyData ultimateParent = null;

  @SerializedName("ImmediateParent")
  private CompanyData immediateParent = null;

  @SerializedName("SubsidiaryCompanies")
  private List<CompanyData> subsidiaryCompanies = null;

  @SerializedName("AffiliatedCompanies")
  private List<CompanyData> affiliatedCompanies = null;

  public LtdGroupStructure ultimateParent(CompanyData ultimateParent) {
    this.ultimateParent = ultimateParent;
    return this;
  }

   /**
   * Get ultimateParent
   * @return ultimateParent
  **/
  @ApiModelProperty(value = "")
  public CompanyData getUltimateParent() {
    return ultimateParent;
  }

  public void setUltimateParent(CompanyData ultimateParent) {
    this.ultimateParent = ultimateParent;
  }

  public LtdGroupStructure immediateParent(CompanyData immediateParent) {
    this.immediateParent = immediateParent;
    return this;
  }

   /**
   * Get immediateParent
   * @return immediateParent
  **/
  @ApiModelProperty(value = "")
  public CompanyData getImmediateParent() {
    return immediateParent;
  }

  public void setImmediateParent(CompanyData immediateParent) {
    this.immediateParent = immediateParent;
  }

  public LtdGroupStructure subsidiaryCompanies(List<CompanyData> subsidiaryCompanies) {
    this.subsidiaryCompanies = subsidiaryCompanies;
    return this;
  }

  public LtdGroupStructure addSubsidiaryCompaniesItem(CompanyData subsidiaryCompaniesItem) {
    if (this.subsidiaryCompanies == null) {
      this.subsidiaryCompanies = new ArrayList<CompanyData>();
    }
    this.subsidiaryCompanies.add(subsidiaryCompaniesItem);
    return this;
  }

   /**
   * Get subsidiaryCompanies
   * @return subsidiaryCompanies
  **/
  @ApiModelProperty(value = "")
  public List<CompanyData> getSubsidiaryCompanies() {
    return subsidiaryCompanies;
  }

  public void setSubsidiaryCompanies(List<CompanyData> subsidiaryCompanies) {
    this.subsidiaryCompanies = subsidiaryCompanies;
  }

  public LtdGroupStructure affiliatedCompanies(List<CompanyData> affiliatedCompanies) {
    this.affiliatedCompanies = affiliatedCompanies;
    return this;
  }

  public LtdGroupStructure addAffiliatedCompaniesItem(CompanyData affiliatedCompaniesItem) {
    if (this.affiliatedCompanies == null) {
      this.affiliatedCompanies = new ArrayList<CompanyData>();
    }
    this.affiliatedCompanies.add(affiliatedCompaniesItem);
    return this;
  }

   /**
   * Get affiliatedCompanies
   * @return affiliatedCompanies
  **/
  @ApiModelProperty(value = "")
  public List<CompanyData> getAffiliatedCompanies() {
    return affiliatedCompanies;
  }

  public void setAffiliatedCompanies(List<CompanyData> affiliatedCompanies) {
    this.affiliatedCompanies = affiliatedCompanies;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LtdGroupStructure ltdGroupStructure = (LtdGroupStructure) o;
    return Objects.equals(this.ultimateParent, ltdGroupStructure.ultimateParent) &&
        Objects.equals(this.immediateParent, ltdGroupStructure.immediateParent) &&
        Objects.equals(this.subsidiaryCompanies, ltdGroupStructure.subsidiaryCompanies) &&
        Objects.equals(this.affiliatedCompanies, ltdGroupStructure.affiliatedCompanies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ultimateParent, immediateParent, subsidiaryCompanies, affiliatedCompanies);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LtdGroupStructure {\n");
    
    sb.append("    ultimateParent: ").append(toIndentedString(ultimateParent)).append("\n");
    sb.append("    immediateParent: ").append(toIndentedString(immediateParent)).append("\n");
    sb.append("    subsidiaryCompanies: ").append(toIndentedString(subsidiaryCompanies)).append("\n");
    sb.append("    affiliatedCompanies: ").append(toIndentedString(affiliatedCompanies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

