/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OneTimePasswordResultPart
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class OneTimePasswordResultPart {
  @SerializedName("Number")
  private String number = null;

  @SerializedName("PhoneMatchSources")
  private Integer phoneMatchSources = null;

  @SerializedName("Status")
  private Integer status = null;

  @SerializedName("IndicatedStatus")
  private String indicatedStatus = null;

  @SerializedName("IndicatedLocation")
  private String indicatedLocation = null;

  @SerializedName("Result")
  private String result = null;

  public OneTimePasswordResultPart number(String number) {
    this.number = number;
    return this;
  }

   /**
   * Get number
   * @return number
  **/
  @ApiModelProperty(value = "")
  public String getNumber() {
    return number;
  }

  public void setNumber(String number) {
    this.number = number;
  }

  public OneTimePasswordResultPart phoneMatchSources(Integer phoneMatchSources) {
    this.phoneMatchSources = phoneMatchSources;
    return this;
  }

   /**
   * Get phoneMatchSources
   * @return phoneMatchSources
  **/
  @ApiModelProperty(value = "")
  public Integer getPhoneMatchSources() {
    return phoneMatchSources;
  }

  public void setPhoneMatchSources(Integer phoneMatchSources) {
    this.phoneMatchSources = phoneMatchSources;
  }

  public OneTimePasswordResultPart status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public OneTimePasswordResultPart indicatedStatus(String indicatedStatus) {
    this.indicatedStatus = indicatedStatus;
    return this;
  }

   /**
   * Get indicatedStatus
   * @return indicatedStatus
  **/
  @ApiModelProperty(value = "")
  public String getIndicatedStatus() {
    return indicatedStatus;
  }

  public void setIndicatedStatus(String indicatedStatus) {
    this.indicatedStatus = indicatedStatus;
  }

  public OneTimePasswordResultPart indicatedLocation(String indicatedLocation) {
    this.indicatedLocation = indicatedLocation;
    return this;
  }

   /**
   * Get indicatedLocation
   * @return indicatedLocation
  **/
  @ApiModelProperty(value = "")
  public String getIndicatedLocation() {
    return indicatedLocation;
  }

  public void setIndicatedLocation(String indicatedLocation) {
    this.indicatedLocation = indicatedLocation;
  }

  public OneTimePasswordResultPart result(String result) {
    this.result = result;
    return this;
  }

   /**
   * Get result
   * @return result
  **/
  @ApiModelProperty(value = "")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OneTimePasswordResultPart oneTimePasswordResultPart = (OneTimePasswordResultPart) o;
    return Objects.equals(this.number, oneTimePasswordResultPart.number) &&
        Objects.equals(this.phoneMatchSources, oneTimePasswordResultPart.phoneMatchSources) &&
        Objects.equals(this.status, oneTimePasswordResultPart.status) &&
        Objects.equals(this.indicatedStatus, oneTimePasswordResultPart.indicatedStatus) &&
        Objects.equals(this.indicatedLocation, oneTimePasswordResultPart.indicatedLocation) &&
        Objects.equals(this.result, oneTimePasswordResultPart.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, phoneMatchSources, status, indicatedStatus, indicatedLocation, result);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OneTimePasswordResultPart {\n");
    
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    phoneMatchSources: ").append(toIndentedString(phoneMatchSources)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    indicatedStatus: ").append(toIndentedString(indicatedStatus)).append("\n");
    sb.append("    indicatedLocation: ").append(toIndentedString(indicatedLocation)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

