/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.OneTimePasswordResultPart;
import java.io.IOException;

/**
 * OneTimePasswordPart
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class OneTimePasswordPart {
  @SerializedName("Landline1")
  private OneTimePasswordResultPart landline1 = null;

  @SerializedName("Landline2")
  private OneTimePasswordResultPart landline2 = null;

  @SerializedName("Mobile1")
  private OneTimePasswordResultPart mobile1 = null;

  @SerializedName("Mobile2")
  private OneTimePasswordResultPart mobile2 = null;

  public OneTimePasswordPart landline1(OneTimePasswordResultPart landline1) {
    this.landline1 = landline1;
    return this;
  }

   /**
   * Get landline1
   * @return landline1
  **/
  @ApiModelProperty(value = "")
  public OneTimePasswordResultPart getLandline1() {
    return landline1;
  }

  public void setLandline1(OneTimePasswordResultPart landline1) {
    this.landline1 = landline1;
  }

  public OneTimePasswordPart landline2(OneTimePasswordResultPart landline2) {
    this.landline2 = landline2;
    return this;
  }

   /**
   * Get landline2
   * @return landline2
  **/
  @ApiModelProperty(value = "")
  public OneTimePasswordResultPart getLandline2() {
    return landline2;
  }

  public void setLandline2(OneTimePasswordResultPart landline2) {
    this.landline2 = landline2;
  }

  public OneTimePasswordPart mobile1(OneTimePasswordResultPart mobile1) {
    this.mobile1 = mobile1;
    return this;
  }

   /**
   * Get mobile1
   * @return mobile1
  **/
  @ApiModelProperty(value = "")
  public OneTimePasswordResultPart getMobile1() {
    return mobile1;
  }

  public void setMobile1(OneTimePasswordResultPart mobile1) {
    this.mobile1 = mobile1;
  }

  public OneTimePasswordPart mobile2(OneTimePasswordResultPart mobile2) {
    this.mobile2 = mobile2;
    return this;
  }

   /**
   * Get mobile2
   * @return mobile2
  **/
  @ApiModelProperty(value = "")
  public OneTimePasswordResultPart getMobile2() {
    return mobile2;
  }

  public void setMobile2(OneTimePasswordResultPart mobile2) {
    this.mobile2 = mobile2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OneTimePasswordPart oneTimePasswordPart = (OneTimePasswordPart) o;
    return Objects.equals(this.landline1, oneTimePasswordPart.landline1) &&
        Objects.equals(this.landline2, oneTimePasswordPart.landline2) &&
        Objects.equals(this.mobile1, oneTimePasswordPart.mobile1) &&
        Objects.equals(this.mobile2, oneTimePasswordPart.mobile2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(landline1, landline2, mobile1, mobile2);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OneTimePasswordPart {\n");
    
    sb.append("    landline1: ").append(toIndentedString(landline1)).append("\n");
    sb.append("    landline2: ").append(toIndentedString(landline2)).append("\n");
    sb.append("    mobile1: ").append(toIndentedString(mobile1)).append("\n");
    sb.append("    mobile2: ").append(toIndentedString(mobile2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

