/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * PreviousName
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class PreviousName {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("DateChanged")
  private DateTime dateChanged = null;

  @SerializedName("DateChangedSpecified")
  private Boolean dateChangedSpecified = null;

  public PreviousName name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PreviousName dateChanged(DateTime dateChanged) {
    this.dateChanged = dateChanged;
    return this;
  }

   /**
   * Get dateChanged
   * @return dateChanged
  **/
  @ApiModelProperty(value = "")
  public DateTime getDateChanged() {
    return dateChanged;
  }

  public void setDateChanged(DateTime dateChanged) {
    this.dateChanged = dateChanged;
  }

  public PreviousName dateChangedSpecified(Boolean dateChangedSpecified) {
    this.dateChangedSpecified = dateChangedSpecified;
    return this;
  }

   /**
   * Get dateChangedSpecified
   * @return dateChangedSpecified
  **/
  @ApiModelProperty(value = "")
  public Boolean getDateChangedSpecified() {
    return dateChangedSpecified;
  }

  public void setDateChangedSpecified(Boolean dateChangedSpecified) {
    this.dateChangedSpecified = dateChangedSpecified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreviousName previousName = (PreviousName) o;
    return Objects.equals(this.name, previousName.name) &&
        Objects.equals(this.dateChanged, previousName.dateChanged) &&
        Objects.equals(this.dateChangedSpecified, previousName.dateChangedSpecified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, dateChanged, dateChangedSpecified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PreviousName {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dateChanged: ").append(toIndentedString(dateChanged)).append("\n");
    sb.append("    dateChangedSpecified: ").append(toIndentedString(dateChangedSpecified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

