/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PrsPart
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class PrsPart {
  @SerializedName("MatchResult")
  private String matchResult = null;

  @SerializedName("PropertyOwnership")
  private String propertyOwnership = null;

  @SerializedName("TitleNumber")
  private String titleNumber = null;

  public PrsPart matchResult(String matchResult) {
    this.matchResult = matchResult;
    return this;
  }

   /**
   * Get matchResult
   * @return matchResult
  **/
  @ApiModelProperty(value = "")
  public String getMatchResult() {
    return matchResult;
  }

  public void setMatchResult(String matchResult) {
    this.matchResult = matchResult;
  }

  public PrsPart propertyOwnership(String propertyOwnership) {
    this.propertyOwnership = propertyOwnership;
    return this;
  }

   /**
   * Get propertyOwnership
   * @return propertyOwnership
  **/
  @ApiModelProperty(value = "")
  public String getPropertyOwnership() {
    return propertyOwnership;
  }

  public void setPropertyOwnership(String propertyOwnership) {
    this.propertyOwnership = propertyOwnership;
  }

  public PrsPart titleNumber(String titleNumber) {
    this.titleNumber = titleNumber;
    return this;
  }

   /**
   * Get titleNumber
   * @return titleNumber
  **/
  @ApiModelProperty(value = "")
  public String getTitleNumber() {
    return titleNumber;
  }

  public void setTitleNumber(String titleNumber) {
    this.titleNumber = titleNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrsPart prsPart = (PrsPart) o;
    return Objects.equals(this.matchResult, prsPart.matchResult) &&
        Objects.equals(this.propertyOwnership, prsPart.propertyOwnership) &&
        Objects.equals(this.titleNumber, prsPart.titleNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchResult, propertyOwnership, titleNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrsPart {\n");
    
    sb.append("    matchResult: ").append(toIndentedString(matchResult)).append("\n");
    sb.append("    propertyOwnership: ").append(toIndentedString(propertyOwnership)).append("\n");
    sb.append("    titleNumber: ").append(toIndentedString(titleNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

