/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SearchActivityHistoryPart
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class SearchActivityHistoryPart {
  @SerializedName("Date")
  private String date = null;

  @SerializedName("BusinessActivity")
  private String businessActivity = null;

  public SearchActivityHistoryPart date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public SearchActivityHistoryPart businessActivity(String businessActivity) {
    this.businessActivity = businessActivity;
    return this;
  }

   /**
   * Get businessActivity
   * @return businessActivity
  **/
  @ApiModelProperty(value = "")
  public String getBusinessActivity() {
    return businessActivity;
  }

  public void setBusinessActivity(String businessActivity) {
    this.businessActivity = businessActivity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchActivityHistoryPart searchActivityHistoryPart = (SearchActivityHistoryPart) o;
    return Objects.equals(this.date, searchActivityHistoryPart.date) &&
        Objects.equals(this.businessActivity, searchActivityHistoryPart.businessActivity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, businessActivity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchActivityHistoryPart {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    businessActivity: ").append(toIndentedString(businessActivity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

