/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SearchActivityHistoryPart;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SearchActivityPart
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class SearchActivityPart {
  @SerializedName("ProfileType")
  private String profileType = null;

  @SerializedName("OneMonth")
  private Integer oneMonth = null;

  @SerializedName("ThreeMonth")
  private Integer threeMonth = null;

  @SerializedName("SixMonth")
  private Integer sixMonth = null;

  @SerializedName("History")
  private List<SearchActivityHistoryPart> history = null;

  public SearchActivityPart profileType(String profileType) {
    this.profileType = profileType;
    return this;
  }

   /**
   * Get profileType
   * @return profileType
  **/
  @ApiModelProperty(value = "")
  public String getProfileType() {
    return profileType;
  }

  public void setProfileType(String profileType) {
    this.profileType = profileType;
  }

  public SearchActivityPart oneMonth(Integer oneMonth) {
    this.oneMonth = oneMonth;
    return this;
  }

   /**
   * Get oneMonth
   * @return oneMonth
  **/
  @ApiModelProperty(value = "")
  public Integer getOneMonth() {
    return oneMonth;
  }

  public void setOneMonth(Integer oneMonth) {
    this.oneMonth = oneMonth;
  }

  public SearchActivityPart threeMonth(Integer threeMonth) {
    this.threeMonth = threeMonth;
    return this;
  }

   /**
   * Get threeMonth
   * @return threeMonth
  **/
  @ApiModelProperty(value = "")
  public Integer getThreeMonth() {
    return threeMonth;
  }

  public void setThreeMonth(Integer threeMonth) {
    this.threeMonth = threeMonth;
  }

  public SearchActivityPart sixMonth(Integer sixMonth) {
    this.sixMonth = sixMonth;
    return this;
  }

   /**
   * Get sixMonth
   * @return sixMonth
  **/
  @ApiModelProperty(value = "")
  public Integer getSixMonth() {
    return sixMonth;
  }

  public void setSixMonth(Integer sixMonth) {
    this.sixMonth = sixMonth;
  }

  public SearchActivityPart history(List<SearchActivityHistoryPart> history) {
    this.history = history;
    return this;
  }

  public SearchActivityPart addHistoryItem(SearchActivityHistoryPart historyItem) {
    if (this.history == null) {
      this.history = new ArrayList<SearchActivityHistoryPart>();
    }
    this.history.add(historyItem);
    return this;
  }

   /**
   * Get history
   * @return history
  **/
  @ApiModelProperty(value = "")
  public List<SearchActivityHistoryPart> getHistory() {
    return history;
  }

  public void setHistory(List<SearchActivityHistoryPart> history) {
    this.history = history;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchActivityPart searchActivityPart = (SearchActivityPart) o;
    return Objects.equals(this.profileType, searchActivityPart.profileType) &&
        Objects.equals(this.oneMonth, searchActivityPart.oneMonth) &&
        Objects.equals(this.threeMonth, searchActivityPart.threeMonth) &&
        Objects.equals(this.sixMonth, searchActivityPart.sixMonth) &&
        Objects.equals(this.history, searchActivityPart.history);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileType, oneMonth, threeMonth, sixMonth, history);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchActivityPart {\n");
    
    sb.append("    profileType: ").append(toIndentedString(profileType)).append("\n");
    sb.append("    oneMonth: ").append(toIndentedString(oneMonth)).append("\n");
    sb.append("    threeMonth: ").append(toIndentedString(threeMonth)).append("\n");
    sb.append("    sixMonth: ").append(toIndentedString(sixMonth)).append("\n");
    sb.append("    history: ").append(toIndentedString(history)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

