/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AddressLabel;
import java.io.IOException;

/**
 * SmartlinkPart
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class SmartlinkPart {
  @SerializedName("Title")
  private String title = null;

  @SerializedName("Forename")
  private String forename = null;

  @SerializedName("Middle")
  private String middle = null;

  @SerializedName("Surname")
  private String surname = null;

  @SerializedName("DOB")
  private String DOB = null;

  @SerializedName("Address")
  private AddressLabel address = null;

  @SerializedName("Recency")
  private String recency = null;

  @SerializedName("Residency")
  private String residency = null;

  @SerializedName("LinkSource")
  private String linkSource = null;

  public SmartlinkPart title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public SmartlinkPart forename(String forename) {
    this.forename = forename;
    return this;
  }

   /**
   * Get forename
   * @return forename
  **/
  @ApiModelProperty(value = "")
  public String getForename() {
    return forename;
  }

  public void setForename(String forename) {
    this.forename = forename;
  }

  public SmartlinkPart middle(String middle) {
    this.middle = middle;
    return this;
  }

   /**
   * Get middle
   * @return middle
  **/
  @ApiModelProperty(value = "")
  public String getMiddle() {
    return middle;
  }

  public void setMiddle(String middle) {
    this.middle = middle;
  }

  public SmartlinkPart surname(String surname) {
    this.surname = surname;
    return this;
  }

   /**
   * Get surname
   * @return surname
  **/
  @ApiModelProperty(value = "")
  public String getSurname() {
    return surname;
  }

  public void setSurname(String surname) {
    this.surname = surname;
  }

  public SmartlinkPart DOB(String DOB) {
    this.DOB = DOB;
    return this;
  }

   /**
   * Get DOB
   * @return DOB
  **/
  @ApiModelProperty(value = "")
  public String getDOB() {
    return DOB;
  }

  public void setDOB(String DOB) {
    this.DOB = DOB;
  }

  public SmartlinkPart address(AddressLabel address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public AddressLabel getAddress() {
    return address;
  }

  public void setAddress(AddressLabel address) {
    this.address = address;
  }

  public SmartlinkPart recency(String recency) {
    this.recency = recency;
    return this;
  }

   /**
   * Get recency
   * @return recency
  **/
  @ApiModelProperty(value = "")
  public String getRecency() {
    return recency;
  }

  public void setRecency(String recency) {
    this.recency = recency;
  }

  public SmartlinkPart residency(String residency) {
    this.residency = residency;
    return this;
  }

   /**
   * Get residency
   * @return residency
  **/
  @ApiModelProperty(value = "")
  public String getResidency() {
    return residency;
  }

  public void setResidency(String residency) {
    this.residency = residency;
  }

  public SmartlinkPart linkSource(String linkSource) {
    this.linkSource = linkSource;
    return this;
  }

   /**
   * Get linkSource
   * @return linkSource
  **/
  @ApiModelProperty(value = "")
  public String getLinkSource() {
    return linkSource;
  }

  public void setLinkSource(String linkSource) {
    this.linkSource = linkSource;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SmartlinkPart smartlinkPart = (SmartlinkPart) o;
    return Objects.equals(this.title, smartlinkPart.title) &&
        Objects.equals(this.forename, smartlinkPart.forename) &&
        Objects.equals(this.middle, smartlinkPart.middle) &&
        Objects.equals(this.surname, smartlinkPart.surname) &&
        Objects.equals(this.DOB, smartlinkPart.DOB) &&
        Objects.equals(this.address, smartlinkPart.address) &&
        Objects.equals(this.recency, smartlinkPart.recency) &&
        Objects.equals(this.residency, smartlinkPart.residency) &&
        Objects.equals(this.linkSource, smartlinkPart.linkSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, forename, middle, surname, DOB, address, recency, residency, linkSource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SmartlinkPart {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    forename: ").append(toIndentedString(forename)).append("\n");
    sb.append("    middle: ").append(toIndentedString(middle)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    DOB: ").append(toIndentedString(DOB)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    recency: ").append(toIndentedString(recency)).append("\n");
    sb.append("    residency: ").append(toIndentedString(residency)).append("\n");
    sb.append("    linkSource: ").append(toIndentedString(linkSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

