/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ErrorPart;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SummaryPart
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class SummaryPart {
  @SerializedName("Status")
  private Boolean status = null;

  @SerializedName("ID")
  private String ID = null;

  @SerializedName("IKey")
  private String ikey = null;

  @SerializedName("equifaxUsername")
  private String equifaxUsername = null;

  @SerializedName("Reference")
  private String reference = null;

  @SerializedName("Scorecard")
  private String scorecard = null;

  @SerializedName("Smartscore")
  private Integer smartscore = null;

  @SerializedName("ResultText")
  private String resultText = null;

  @SerializedName("ProfileURL")
  private String profileURL = null;

  @SerializedName("Credits")
  private Integer credits = null;

  @SerializedName("Errors")
  private List<ErrorPart> errors = null;

  public SummaryPart status(Boolean status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public Boolean getStatus() {
    return status;
  }

  public void setStatus(Boolean status) {
    this.status = status;
  }

  public SummaryPart ID(String ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @ApiModelProperty(value = "")
  public String getID() {
    return ID;
  }

  public void setID(String ID) {
    this.ID = ID;
  }

  public SummaryPart ikey(String ikey) {
    this.ikey = ikey;
    return this;
  }

   /**
   * Get ikey
   * @return ikey
  **/
  @ApiModelProperty(value = "")
  public String getIkey() {
    return ikey;
  }

  public void setIkey(String ikey) {
    this.ikey = ikey;
  }

  public SummaryPart equifaxUsername(String equifaxUsername) {
    this.equifaxUsername = equifaxUsername;
    return this;
  }

   /**
   * Get equifaxUsername
   * @return equifaxUsername
  **/
  @ApiModelProperty(value = "")
  public String getEquifaxUsername() {
    return equifaxUsername;
  }

  public void setEquifaxUsername(String equifaxUsername) {
    this.equifaxUsername = equifaxUsername;
  }

  public SummaryPart reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(value = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public SummaryPart scorecard(String scorecard) {
    this.scorecard = scorecard;
    return this;
  }

   /**
   * Get scorecard
   * @return scorecard
  **/
  @ApiModelProperty(value = "")
  public String getScorecard() {
    return scorecard;
  }

  public void setScorecard(String scorecard) {
    this.scorecard = scorecard;
  }

  public SummaryPart smartscore(Integer smartscore) {
    this.smartscore = smartscore;
    return this;
  }

   /**
   * Get smartscore
   * @return smartscore
  **/
  @ApiModelProperty(value = "")
  public Integer getSmartscore() {
    return smartscore;
  }

  public void setSmartscore(Integer smartscore) {
    this.smartscore = smartscore;
  }

  public SummaryPart resultText(String resultText) {
    this.resultText = resultText;
    return this;
  }

   /**
   * Get resultText
   * @return resultText
  **/
  @ApiModelProperty(value = "")
  public String getResultText() {
    return resultText;
  }

  public void setResultText(String resultText) {
    this.resultText = resultText;
  }

  public SummaryPart profileURL(String profileURL) {
    this.profileURL = profileURL;
    return this;
  }

   /**
   * Get profileURL
   * @return profileURL
  **/
  @ApiModelProperty(value = "")
  public String getProfileURL() {
    return profileURL;
  }

  public void setProfileURL(String profileURL) {
    this.profileURL = profileURL;
  }

  public SummaryPart credits(Integer credits) {
    this.credits = credits;
    return this;
  }

   /**
   * Get credits
   * @return credits
  **/
  @ApiModelProperty(value = "")
  public Integer getCredits() {
    return credits;
  }

  public void setCredits(Integer credits) {
    this.credits = credits;
  }

  public SummaryPart errors(List<ErrorPart> errors) {
    this.errors = errors;
    return this;
  }

  public SummaryPart addErrorsItem(ErrorPart errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<ErrorPart>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  @ApiModelProperty(value = "")
  public List<ErrorPart> getErrors() {
    return errors;
  }

  public void setErrors(List<ErrorPart> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SummaryPart summaryPart = (SummaryPart) o;
    return Objects.equals(this.status, summaryPart.status) &&
        Objects.equals(this.ID, summaryPart.ID) &&
        Objects.equals(this.ikey, summaryPart.ikey) &&
        Objects.equals(this.equifaxUsername, summaryPart.equifaxUsername) &&
        Objects.equals(this.reference, summaryPart.reference) &&
        Objects.equals(this.scorecard, summaryPart.scorecard) &&
        Objects.equals(this.smartscore, summaryPart.smartscore) &&
        Objects.equals(this.resultText, summaryPart.resultText) &&
        Objects.equals(this.profileURL, summaryPart.profileURL) &&
        Objects.equals(this.credits, summaryPart.credits) &&
        Objects.equals(this.errors, summaryPart.errors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, ID, ikey, equifaxUsername, reference, scorecard, smartscore, resultText, profileURL, credits, errors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SummaryPart {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    ikey: ").append(toIndentedString(ikey)).append("\n");
    sb.append("    equifaxUsername: ").append(toIndentedString(equifaxUsername)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    scorecard: ").append(toIndentedString(scorecard)).append("\n");
    sb.append("    smartscore: ").append(toIndentedString(smartscore)).append("\n");
    sb.append("    resultText: ").append(toIndentedString(resultText)).append("\n");
    sb.append("    profileURL: ").append(toIndentedString(profileURL)).append("\n");
    sb.append("    credits: ").append(toIndentedString(credits)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

