/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TravelVisaTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class TravelVisaTO {
  @SerializedName("line1")
  private String line1 = null;

  @SerializedName("line2")
  private String line2 = null;

  @SerializedName("line3")
  private String line3 = null;

  @SerializedName("line4")
  private String line4 = null;

  @SerializedName("line5")
  private String line5 = null;

  @SerializedName("line6")
  private String line6 = null;

  @SerializedName("line7")
  private String line7 = null;

  @SerializedName("line8")
  private String line8 = null;

  @SerializedName("line9")
  private String line9 = null;

  public TravelVisaTO line1(String line1) {
    this.line1 = line1;
    return this;
  }

   /**
   * Get line1
   * @return line1
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLine1() {
    return line1;
  }

  public void setLine1(String line1) {
    this.line1 = line1;
  }

  public TravelVisaTO line2(String line2) {
    this.line2 = line2;
    return this;
  }

   /**
   * Get line2
   * @return line2
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLine2() {
    return line2;
  }

  public void setLine2(String line2) {
    this.line2 = line2;
  }

  public TravelVisaTO line3(String line3) {
    this.line3 = line3;
    return this;
  }

   /**
   * Get line3
   * @return line3
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLine3() {
    return line3;
  }

  public void setLine3(String line3) {
    this.line3 = line3;
  }

  public TravelVisaTO line4(String line4) {
    this.line4 = line4;
    return this;
  }

   /**
   * Get line4
   * @return line4
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLine4() {
    return line4;
  }

  public void setLine4(String line4) {
    this.line4 = line4;
  }

  public TravelVisaTO line5(String line5) {
    this.line5 = line5;
    return this;
  }

   /**
   * Get line5
   * @return line5
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLine5() {
    return line5;
  }

  public void setLine5(String line5) {
    this.line5 = line5;
  }

  public TravelVisaTO line6(String line6) {
    this.line6 = line6;
    return this;
  }

   /**
   * Get line6
   * @return line6
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLine6() {
    return line6;
  }

  public void setLine6(String line6) {
    this.line6 = line6;
  }

  public TravelVisaTO line7(String line7) {
    this.line7 = line7;
    return this;
  }

   /**
   * Get line7
   * @return line7
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLine7() {
    return line7;
  }

  public void setLine7(String line7) {
    this.line7 = line7;
  }

  public TravelVisaTO line8(String line8) {
    this.line8 = line8;
    return this;
  }

   /**
   * Get line8
   * @return line8
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLine8() {
    return line8;
  }

  public void setLine8(String line8) {
    this.line8 = line8;
  }

  public TravelVisaTO line9(String line9) {
    this.line9 = line9;
    return this;
  }

   /**
   * Get line9
   * @return line9
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLine9() {
    return line9;
  }

  public void setLine9(String line9) {
    this.line9 = line9;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TravelVisaTO travelVisaTO = (TravelVisaTO) o;
    return Objects.equals(this.line1, travelVisaTO.line1) &&
        Objects.equals(this.line2, travelVisaTO.line2) &&
        Objects.equals(this.line3, travelVisaTO.line3) &&
        Objects.equals(this.line4, travelVisaTO.line4) &&
        Objects.equals(this.line5, travelVisaTO.line5) &&
        Objects.equals(this.line6, travelVisaTO.line6) &&
        Objects.equals(this.line7, travelVisaTO.line7) &&
        Objects.equals(this.line8, travelVisaTO.line8) &&
        Objects.equals(this.line9, travelVisaTO.line9);
  }

  @Override
  public int hashCode() {
    return Objects.hash(line1, line2, line3, line4, line5, line6, line7, line8, line9);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TravelVisaTO {\n");
    
    sb.append("    line1: ").append(toIndentedString(line1)).append("\n");
    sb.append("    line2: ").append(toIndentedString(line2)).append("\n");
    sb.append("    line3: ").append(toIndentedString(line3)).append("\n");
    sb.append("    line4: ").append(toIndentedString(line4)).append("\n");
    sb.append("    line5: ").append(toIndentedString(line5)).append("\n");
    sb.append("    line6: ").append(toIndentedString(line6)).append("\n");
    sb.append("    line7: ").append(toIndentedString(line7)).append("\n");
    sb.append("    line8: ").append(toIndentedString(line8)).append("\n");
    sb.append("    line9: ").append(toIndentedString(line9)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

