/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TravelVisaPart
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class TravelVisaPart {
  @SerializedName("MRZValid")
  private Boolean mrZValid = null;

  @SerializedName("InDate")
  private Boolean inDate = null;

  @SerializedName("UKResidenceValid")
  private Boolean ukResidenceValid = null;

  public TravelVisaPart mrZValid(Boolean mrZValid) {
    this.mrZValid = mrZValid;
    return this;
  }

   /**
   * Get mrZValid
   * @return mrZValid
  **/
  @ApiModelProperty(value = "")
  public Boolean getMrZValid() {
    return mrZValid;
  }

  public void setMrZValid(Boolean mrZValid) {
    this.mrZValid = mrZValid;
  }

  public TravelVisaPart inDate(Boolean inDate) {
    this.inDate = inDate;
    return this;
  }

   /**
   * Get inDate
   * @return inDate
  **/
  @ApiModelProperty(value = "")
  public Boolean getInDate() {
    return inDate;
  }

  public void setInDate(Boolean inDate) {
    this.inDate = inDate;
  }

  public TravelVisaPart ukResidenceValid(Boolean ukResidenceValid) {
    this.ukResidenceValid = ukResidenceValid;
    return this;
  }

   /**
   * Get ukResidenceValid
   * @return ukResidenceValid
  **/
  @ApiModelProperty(value = "")
  public Boolean getUkResidenceValid() {
    return ukResidenceValid;
  }

  public void setUkResidenceValid(Boolean ukResidenceValid) {
    this.ukResidenceValid = ukResidenceValid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TravelVisaPart travelVisaPart = (TravelVisaPart) o;
    return Objects.equals(this.mrZValid, travelVisaPart.mrZValid) &&
        Objects.equals(this.inDate, travelVisaPart.inDate) &&
        Objects.equals(this.ukResidenceValid, travelVisaPart.ukResidenceValid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mrZValid, inDate, ukResidenceValid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TravelVisaPart {\n");
    
    sb.append("    mrZValid: ").append(toIndentedString(mrZValid)).append("\n");
    sb.append("    inDate: ").append(toIndentedString(inDate)).append("\n");
    sb.append("    ukResidenceValid: ").append(toIndentedString(ukResidenceValid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

