/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CompanySearchResultsTO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * VeriphyCompanySearchResponseTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class VeriphyCompanySearchResponseTO {
  @SerializedName("reference")
  private String reference = null;

  @SerializedName("veriphyCheckId")
  private String veriphyCheckId = null;

  @SerializedName("companyList")
  private List<CompanySearchResultsTO> companyList = null;

  public VeriphyCompanySearchResponseTO reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(value = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public VeriphyCompanySearchResponseTO veriphyCheckId(String veriphyCheckId) {
    this.veriphyCheckId = veriphyCheckId;
    return this;
  }

   /**
   * Get veriphyCheckId
   * @return veriphyCheckId
  **/
  @ApiModelProperty(value = "")
  public String getVeriphyCheckId() {
    return veriphyCheckId;
  }

  public void setVeriphyCheckId(String veriphyCheckId) {
    this.veriphyCheckId = veriphyCheckId;
  }

  public VeriphyCompanySearchResponseTO companyList(List<CompanySearchResultsTO> companyList) {
    this.companyList = companyList;
    return this;
  }

  public VeriphyCompanySearchResponseTO addCompanyListItem(CompanySearchResultsTO companyListItem) {
    if (this.companyList == null) {
      this.companyList = new ArrayList<CompanySearchResultsTO>();
    }
    this.companyList.add(companyListItem);
    return this;
  }

   /**
   * Get companyList
   * @return companyList
  **/
  @ApiModelProperty(value = "")
  public List<CompanySearchResultsTO> getCompanyList() {
    return companyList;
  }

  public void setCompanyList(List<CompanySearchResultsTO> companyList) {
    this.companyList = companyList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VeriphyCompanySearchResponseTO veriphyCompanySearchResponseTO = (VeriphyCompanySearchResponseTO) o;
    return Objects.equals(this.reference, veriphyCompanySearchResponseTO.reference) &&
        Objects.equals(this.veriphyCheckId, veriphyCompanySearchResponseTO.veriphyCheckId) &&
        Objects.equals(this.companyList, veriphyCompanySearchResponseTO.companyList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reference, veriphyCheckId, companyList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VeriphyCompanySearchResponseTO {\n");
    
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    veriphyCheckId: ").append(toIndentedString(veriphyCheckId)).append("\n");
    sb.append("    companyList: ").append(toIndentedString(companyList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

