/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.LtdCompanyFullReport;
import java.io.IOException;

/**
 * VeriphyCompanyResponseTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class VeriphyCompanyResponseTO {
  @SerializedName("reference")
  private String reference = null;

  @SerializedName("responseResult")
  private LtdCompanyFullReport responseResult = null;

  @SerializedName("responseEncodedPdf")
  private String responseEncodedPdf = null;

  @SerializedName("veriphyCheckId")
  private String veriphyCheckId = null;

  public VeriphyCompanyResponseTO reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(value = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public VeriphyCompanyResponseTO responseResult(LtdCompanyFullReport responseResult) {
    this.responseResult = responseResult;
    return this;
  }

   /**
   * Get responseResult
   * @return responseResult
  **/
  @ApiModelProperty(value = "")
  public LtdCompanyFullReport getResponseResult() {
    return responseResult;
  }

  public void setResponseResult(LtdCompanyFullReport responseResult) {
    this.responseResult = responseResult;
  }

  public VeriphyCompanyResponseTO responseEncodedPdf(String responseEncodedPdf) {
    this.responseEncodedPdf = responseEncodedPdf;
    return this;
  }

   /**
   * Get responseEncodedPdf
   * @return responseEncodedPdf
  **/
  @ApiModelProperty(value = "")
  public String getResponseEncodedPdf() {
    return responseEncodedPdf;
  }

  public void setResponseEncodedPdf(String responseEncodedPdf) {
    this.responseEncodedPdf = responseEncodedPdf;
  }

  public VeriphyCompanyResponseTO veriphyCheckId(String veriphyCheckId) {
    this.veriphyCheckId = veriphyCheckId;
    return this;
  }

   /**
   * Get veriphyCheckId
   * @return veriphyCheckId
  **/
  @ApiModelProperty(value = "")
  public String getVeriphyCheckId() {
    return veriphyCheckId;
  }

  public void setVeriphyCheckId(String veriphyCheckId) {
    this.veriphyCheckId = veriphyCheckId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VeriphyCompanyResponseTO veriphyCompanyResponseTO = (VeriphyCompanyResponseTO) o;
    return Objects.equals(this.reference, veriphyCompanyResponseTO.reference) &&
        Objects.equals(this.responseResult, veriphyCompanyResponseTO.responseResult) &&
        Objects.equals(this.responseEncodedPdf, veriphyCompanyResponseTO.responseEncodedPdf) &&
        Objects.equals(this.veriphyCheckId, veriphyCompanyResponseTO.veriphyCheckId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reference, responseResult, responseEncodedPdf, veriphyCheckId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VeriphyCompanyResponseTO {\n");
    
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    responseResult: ").append(toIndentedString(responseResult)).append("\n");
    sb.append("    responseEncodedPdf: ").append(toIndentedString(responseEncodedPdf)).append("\n");
    sb.append("    veriphyCheckId: ").append(toIndentedString(veriphyCheckId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

