/*
 * Veriphy API
 * This API provides access to the ID/AML, Company and Lawyer check services provided by Veriphy. This API is secured - please contact us to request test credentials.<br/>The API can send and receive either JSON or XML - please explore the API methods and the return types/parameters below.
 *
 * OpenAPI spec version: v1
 * Contact: support@veriphy.co.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VeriphyServiceTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-29T17:21:25.566Z")
public class VeriphyServiceTO {
  @SerializedName("returnPDF")
  private Boolean returnPDF = null;

  @SerializedName("serviceCode")
  private String serviceCode = null;

  public VeriphyServiceTO returnPDF(Boolean returnPDF) {
    this.returnPDF = returnPDF;
    return this;
  }

   /**
   * Get returnPDF
   * @return returnPDF
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getReturnPDF() {
    return returnPDF;
  }

  public void setReturnPDF(Boolean returnPDF) {
    this.returnPDF = returnPDF;
  }

  public VeriphyServiceTO serviceCode(String serviceCode) {
    this.serviceCode = serviceCode;
    return this;
  }

   /**
   * Get serviceCode
   * @return serviceCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getServiceCode() {
    return serviceCode;
  }

  public void setServiceCode(String serviceCode) {
    this.serviceCode = serviceCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VeriphyServiceTO veriphyServiceTO = (VeriphyServiceTO) o;
    return Objects.equals(this.returnPDF, veriphyServiceTO.returnPDF) &&
        Objects.equals(this.serviceCode, veriphyServiceTO.serviceCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(returnPDF, serviceCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VeriphyServiceTO {\n");
    
    sb.append("    returnPDF: ").append(toIndentedString(returnPDF)).append("\n");
    sb.append("    serviceCode: ").append(toIndentedString(serviceCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

