name: Build and Release

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 11
          distribution: temurin

      - name: Build
        run: ./gradlew build

      - name: Print Files
        run: ls -LR

      - name: Release
        uses: softprops/action-gh-release@v2.0.4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/*.jar
